\documentclass[11pt]{book}   
\usepackage{Sweave}%% needs to come before resDocSty
\usepackage{resDocSty}%% Res Doc .sty file

%\usepackage{rotating}%% for sideways table
\usepackage{array}
\usepackage{longtable}
\usepackage{pdfcomment}
\usepackage{fmtcount}%% for rendering numbers to words
\usepackage{xcolor, soul}

\usepackage{amssymb}%% https://ctan.org/pkg/amssymb?lang=en
\usepackage{mathtools}%% https://ctan.org/pkg/mathtools?lang=en
\usepackage{MnSymbol}%% https://ctan.org/pkg/mathtools?lang=en

\usepackage{listings}
\lstset{
%basicstyle=\scriptsize\ttfamily,
basicstyle=\tiny\ttfamily,
columns=flexible,
breaklines=true
%escapechar=\%
}

\newcommand{\Lagr}{\mathcal{L}}%% Langrangian L for likelihood
\newcommand{\Norm}{\mathcal{N}}%% Normal distribution
\newcommand{\Fobj}{\mathcal{F}}%% Function objective
\newcommand{\Biom}{\mathcal{B}}%% Mid-season retained dead biomass
\newcommand{\Temp}{\mathcal{T}}%% Temporary variable for Selectivity calcs
\newcommand{\Joyn}{\mathcal{J}}%% Joiner variable for Selectivity calcs (\Join already defined)
\def\bfTh{{\bf \Theta}}%% bold Theta
\newcommand{\dprime}{\prime\prime}%% double prime (supposedly in stix package but it doesn't load properly)
\newcommand{\isactive}{\circledast}%{\circledcirc}%
\newcommand{\inactive}{\vartriangleleft}%
\newcommand{\adj}[1]{\overrightharpoon{#1}}%% adjusted value
\newcommand{\mbull}{$\filledtriangleright$\,}
\newcommand{\nbull}{~~~$\smalltriangleright$\,}

\definecolor{red}{rgb}{1,0,0}
\definecolor{green}{rgb}{0,1,0}
\definecolor{blue}{rgb}{0,0,1}
\definecolor{yellow}{rgb}{1,1,0}
\definecolor{gainsboro}{rgb}{0.8627451,0.8627451,0.8627451}
\definecolor{slategrey}{rgb}{0.4392157, 0.5019608, 0.5647059}
\definecolor{darkslategrey}{rgb}{ 0.1843137 0.3098039 0.3098039}
\definecolor{aliceblue}{RGB}{240, 248, 255}
\definecolor{deepskyblue}{rgb}{0, 0.7490196, 1}
\definecolor{dodgerblue}{RGB}{24, 116, 205}
\definecolor{midnightblue}{rgb}{0.09803922 0.09803922 0.43921569}
\definecolor{moccasin}{RGB}{255, 236, 204}
\definecolor{honeydew}{RGB}{240, 255, 240}
\definecolor{colquote}{RGB}{85, 26, 139}%% purple4 (colour for quotes from Dr. Peoples)
\newcommand{\oldstuff}[1]{\normalsize\textcolor{red}{#1}\normalsize}
\newcommand{\newstuff}[1]{\normalsize\textcolor{blue}{#1}\normalsize}
\newcommand{\greystuff}[1]{\normalsize\textcolor{slategrey}{#1}\normalsize}
\sethlcolor{yellow}

\captionsetup{figurewithin=none,tablewithin=none}%% This works for resetting figure and table numbers for book class though I don't know why. Set fig/table start number to n-1.

\newcommand{\Bmsy}{B_\text{MSY}}
\newcommand{\umsy}{u_\text{MSY}}
\newcommand{\pc}{\%}
\newcommand{\ptype}{png}
\newcommand{\angL}{\guillemotleft\,}
\newcommand{\angR}{\,\guillemotright}

\newcommand{\stock}[1]{$\langle$\,\textcolor{darkslategrey}{#1}\,$\rangle$}
\newcommand{\mr}[1]{\text{#1}}
\newcommand{\super}[1]{$^\mr{#1}$}
\newcommand{\ms}[1]{{\scriptscriptstyle #1}}  %% math small
\newcommand{\mm}[1]{{\scriptstyle #1}}        %% math moderately small
\newcommand{\elof}[1]{\in\left\{#1\right\}}   %% is an element of
\newcommand{\comment}[1]{}                    %% commenting out blocks of text
\newcommand{\commint}[1]{\hspace{-0em}}       %% commenting out in-line text

\def\startP{170}         %% page start (default=1)
\def\startF{0}           %% figure start counter (default=0)
\def\startT{0}           %% table start counter (default=0)

%%http://tex.stackexchange.com/questions/6058/making-a-shorter-minus
\def\minus{%
  \setbox0=\hbox{-}%
  \vcenter{%
    \hrule width\wd0 height 0.05pt% \the\fontdimen8\textfont3%
  }%
}
%%https://tex.stackexchange.com/questions/22100/the-bar-and-overline-commands (Danie Els)
\makeatletter
\newsavebox\myboxA
\newsavebox\myboxB
\newlength\mylenA
\newcommand*\widebar[2][0.75]{%
    \sbox{\myboxA}{$\m@th#2$}%
    \setbox\myboxB\null%% Phantom box
    \ht\myboxB=\ht\myboxA%
    \dp\myboxB=\dp\myboxA%
    \wd\myboxB=#1\wd\myboxA%% Scale phantom
    \sbox\myboxB{$\m@th\overline{\copy\myboxB}$}%% Overlined phantom
    \setlength\mylenA{\the\wd\myboxA}%% calc width diff
    \addtolength\mylenA{-\the\wd\myboxB}%
    \ifdim\wd\myboxB<\wd\myboxA%
       \rlap{\hskip 0.5\mylenA\usebox\myboxB}{\usebox\myboxA}%
    \else
        \hskip -0.5\mylenA\rlap{\usebox\myboxA}{\hskip 0.5\mylenA\usebox\myboxB}%
    \fi}
\makeatother

\makeatletter
\renewcommand{\@chapapp}{}%% Not necessary...
\newenvironment{chapquote}[2][2em]
  {\setlength{\@tempdima}{#1}%
   \def\chapquote@author{#2}%
   \parshape 1 \@tempdima \dimexpr\textwidth-2\@tempdima\relax%
   %\itshape}
   \small\color{colquote}}
  {\par\normalfont\hfill--\ \chapquote@author\hspace*{\@tempdima}\par\smallskip}
\makeatother

\def\ds{\rule{0pt}{1.5ex}}%% push subscript further down (increase vertical spacing)

%% #1=filename, #2=caption text; NOTE: Tags won't work if figure boundaries hit the margins (e.g., keep width < 6.5in)
\newcommand\onefig[2]{
  \begin{figure}[tp]
  \begin{center}
  \pdftooltip{
  \includegraphics[width=6.4in,height=7.25in,keepaspectratio=TRUE]{{#1}.\ptype}}{Figure~\ref{fig:#1}}
  \end{center}
  \caption{#2}
  \label{fig:#1}
  \end{figure}
}
%% #1=fig filename, #2=caption text, #3=fig width, #4=fig height
\newcommand\onefigWH[4]{
  \begin{figure}[tp]
  \begin{center}
  \pdftooltip{
  \includegraphics[width=#3in,height=#4in,keepaspectratio=TRUE]{{#1}.\ptype}}{Figure~\ref{fig:#1}}
  \end{center}
  \caption{#2}
  \label{fig:#1}
  \end{figure}
}
%% #1=fig1 filename, #2=fig2 filename, #3=caption text, #4=fig1 height, #5=fig2 height
\newcommand\twofig[3]{
  \begin{figure}[tp]
  \centering
  \begin{tabular}{c}
  \pdftooltip{
  \includegraphics[width=6in,height=3.5in,keepaspectratio=TRUE]{{#1}.\ptype}}{Figure~\ref{fig:#1} top} \\
  \pdftooltip{
  \includegraphics[width=6in,height=3.5in,keepaspectratio=TRUE]{{#2}.\ptype}}{Figure~\ref{fig:#1} bottom}
  \end{tabular}
  \caption{#3}
  \label{fig:#1}
  \end{figure}
  \clearpage
}
%% #1=fig1 filename, #2=fig2 filename, #3=caption text, #4=fig1 width #5=fig1 height, #6=fig2 width, #7=fig2 height
\newcommand\twofigWH[7]{
  \begin{figure}[tp]
  \centering
  \begin{tabular}{c}
  \pdftooltip{
  \includegraphics[width=#4in,height=#5in,keepaspectratio=TRUE]{{#1}.\ptype}}{Figure~\ref{fig:#1} top} \\
  \pdftooltip{
  \includegraphics[width=#6in,height=#7in,keepaspectratio=TRUE]{{#2}.\ptype}}{Figure~\ref{fig:#1} bottom}
  \end{tabular}
  \caption{#3}
  \label{fig:#1}
  \end{figure}
  \clearpage
}
%% #1=figure1 #2=figure2 #3=label #4=caption #5=width (fig) #6=height (fig)
\newcommand\figbeside[6]{
\begin{figure}[!htp]
  \centering
  \pdftooltip{
  \begin{minipage}[t]{0.47\linewidth}
    \begin{center}
    \includegraphics[width=#5in,height=#6in,keepaspectratio=TRUE]{{#1}.\ptype}
    \end{center}
    %\caption{#3}
    %\label{fig:#1}
  \end{minipage}}{Figure~\ref{fig:#3} left}%
  \quad
  \pdftooltip{
  \begin{minipage}[t]{0.47\linewidth}
    \begin{center}
    \includegraphics[width=#5in,height=#6in,keepaspectratio=TRUE]{{#2}.\ptype}
    \end{center}
    %\caption{#4}
    %\label{fig:#2}
  \end{minipage}}{Figure~\ref{fig:#3} right}
  \caption{#4}
  \label{fig:#3}
\end{figure}
}

\SweaveOpts{pdf=FALSE}        % keep.source=TRUE, 

%% Alter some LaTeX defaults for better treatment of figures:
%% See p.105 of "TeX Unbound" for suggested values.
%% See pp. 199-200 of Lamport's "LaTeX" book for details.
%%   General parameters, for ALL pages:
\renewcommand{\topfraction}{0.95}%% max fraction of floats at top
\renewcommand{\bottomfraction}{0.50}%% max fraction of floats at bottom
%% Parameters for TEXT pages (not float pages):
\setcounter{topnumber}{2}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{4}%% 2 may work better
\renewcommand{\textfraction}{0.05}%% allow minimal text w. figs
%% Parameters for FLOAT pages (not text pages):
\renewcommand{\floatpagefraction}{0.75}%% require fuller float pages
%% N.B.: floatpagefraction MUST be less than topfraction !!

%% Stuff from previous LaTeX equation appendix:
%% -------------------------------------------
  \def\AppLet{E}%%                  Appendix letter
 %\def\schematic{1~}%%              Figure number for schematic fig (in main text)
  \font\mbf=cmmib10 scaled 1200%%   computer modern math italic bold
  \font\sbf=cmbsy10 scaled 1200%%   computer modern symbol bold
  \def\bfmi#1{{\hbox{\mbf #1}}}%%   bold face math italic macro
  \def\bfms#1{{\hbox{\sbf #1}}}%%   bold face math symbol macro
  \def\bfTh{{\bf \Theta}}%%         bold Theta
  \def\bfPh{{\bf \Phi}}%%           bold Phi
  \def\bfleq{\,\bfms{\char'24}\,}%% bold <= (less than or equal)
  \def\bfgeq{\,\bfms{\char'25}\,}%% bold >= (greater than or equal)
  \def\bfeq{\mbox{\bf\,=\,}}%%      bold =
  \def\bft{\bfmi{t}}%%              bold t
  \def\bfT{\bfmi{T}}%%              bold T   - need for headings
  \def\rbT{\mbox{\bf T}}%%          Roman bold T
  \def\rbU{\mbox{\bf U}}%%          Roman bold U
  \def\winf{w_\infty}

  \def\veq{\vspace{-4ex}}%%    contraction around equations
  \def\vec{\vspace{-3ex}}%%    contraction around centering
  %\def\headc{\vspace{-2ex}}%% contraction after 'fake' subsubheading
  \def\headc{\vspace{-1ex}}%%  contraction after 'fake' subsubheading
  %\def\subsub#1{\noindent {\bf #1} \headc}%% fake subheading

% RH commands
\newcommand{\code}[1]{\normalsize\texttt{#1}\normalsize}%
\newcommand\Tstrut{\rule{0pt}{2.6ex}}% top strut
\newcommand\Bstrut{\rule[-1.1ex]{0pt}{0pt}}% bottom strut

\newcolumntype{L}[1]{>{\raggedright\let\newline\\\arraybackslash\hspace{0pt}}p{#1}}%
\newcolumntype{C}[1]{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}p{#1}}%
\newcolumntype{R}[1]{>{\raggedleft\let\newline\\\arraybackslash\hspace{0pt}}p{#1}}%

% AME commands
\newcommand{\inarea}{coastwide}
\newcommand{\AppCat}{Appendix~A}
\newcommand{\AppSurv}{Appendix~B}
\newcommand{\AppCPUE}{Appendix~C}
\newcommand{\AppBio}{Appendix~D}
\newcommand{\AppRes}{Appendix~F}

%% https://tex.stackexchange.com/questions/69662/how-to-globally-change-the-spacing-around-equations
\makeatletter
\g@addto@macro\normalsize{%% This is used for equation control but it interferes with \normalsize unless you add % after each line below
  \setlength\abovedisplayskip{-6pt}%
  \setlength\belowdisplayskip{-6pt}%
  \setlength\abovedisplayshortskip{0pt}%
  \setlength\belowdisplayshortskip{0pt}%
}
\makeatother

\def\vsd{\vspace*{1ex}}%% Aha - there's a whole bunch of these plus -ve
\def\hsd{\hspace*{1ex}}
\def\tab{\hsd\hsd}
\def\newp{\vfill \break}
\def\Var{\mbox{Var}}
\def\Cov{\mbox{Cov}}

%% Equation reference: #1=internal label saved in AUX file
\newcommand{\eref}[1]{(\ref{#1})}

% Revise Andy's usual:
\renewcommand{\eb}{\vsd \vsd \begin{eqnarray}}
\renewcommand{\ee}{\end{eqnarray} \vsd }

%% Repeat this here to override resDocSty (which has math font size 11 a bit smaller)
\DeclareMathSizes{10.95}{12}{8}{4} %% For size 11 math fonts

%%==========================================================

%% Line delimiters in this document:
%% #####  Chapter
%% =====  Section
%% -----  Subsection
%% ~~~~~  Subsubsection
%% +++++  Tables
%% ^^^^^  Figures

\begin{document}
\pagestyle{csapfancy}

\setcounter{page}{\startP}
\setcounter{figure}{\startF}
\setcounter{table}{\startT}
\setcounter{secnumdepth}{3}%% to number subsubheadings-ish
\setlength{\tabcolsep}{3pt}%% table column separator


\setlength\LTleft{0pt plus \textwidth}
\setlength\LTright{0pt plus \textwidth}
%% Fix by David Carlisle for longtable xxx to match that in array
\def\LT@startpbox#1{%
  \bgroup
  \color@begingroup% Omit line if package date older than 2014/10/28
    \let\@footnotetext\LT@p@ftntext
    \setlength\hsize{#1}%
    \@arrayparboxrestore
   \everypar{%
      \vrule \@height \ht\@arstrutbox \@width \z@
      \everypar{}}%
%    \vrule \@height \ht\@arstrutbox \@width \z@
}
%% Default spacing above and below equations
%%\setlength{\abovedisplayskip}{-6pt}
%%\setlength{\belowdisplayskip}{-6pt}

\setcounter{chapter}{5}    % temporary for standalone chapters 9=(5=F, 6=G)
\renewcommand{\thechapter}{\Alph{chapter}} % ditto
\renewcommand{\thesection}{\thechapter.\arabic{section}.}
\renewcommand{\thesubsection}{\thechapter.\arabic{section}.\arabic{subsection}.}
\renewcommand{\thesubsubsection}{\thechapter.\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.}
\renewcommand{\thetable}{\thechapter.\arabic{table}}    
\renewcommand{\thefigure}{\thechapter.\arabic{figure}}  
\renewcommand{\theequation}{\thechapter.\arabic{equation}}
%\renewcommand{\thepage}{\arabic{page}}

\newcounter{prevchapter}
\setcounter{prevchapter}{\value{chapter}}
\addtocounter{prevchapter}{-1}
\newcommand{\eqnchapter}{\Alph{prevchapter}}

<<setupworkspace, echo=FALSE, eval=TRUE, results=hide>>= # hide the results 
##----------------------------
rm(list=setdiff(ls(all=T),c(".First","so","Rcode","qu","Scode")))  ## Start with clean slate

require(PBStools)
## For the Sweave, choose only one language even though some plots will be made in both.
lang = "e"; tput(lang)  ## 'e'=english, 'f'=francais

## Create a subdirectory called `french' for French-language figures if 'f' in lang
createFdir(lang)

pbstoolsDevDir = "C:/Users/haighr/Files/Projects/R/Develop/PBStools/Authors/Rcode/develop/"
scenario=0 ## to source compBmsy without running anything
refresh.PBStools = c("linguaFranca", "changeLangOpts", "compBmsy", "formatCatch", "texArray")
for (i in refresh.PBStools)
	source(paste0(pbstoolsDevDir,i,".r")) ## to ensure the latest code

## Function to deal with lists of g that vary by stock
source("texThatShit.r")

## Set the following for 1 or more stocks:
## --------------------------------------
base.dir   = "C:/Users/haighr/Files/GFish/PSARC23/POP/Docs/WP/AppE_Equations" 
Nstock     = 1
Narea      = 3 ## multi-area stock assessment model (assess coastwide but use multiple areas)
Nsex       = 2
Ngear      = 3  ## even though there are 3 trawl fisheries, this is a coastwide assessment with 3 areas
spp.code   = "POP"
spp.name   = "Pacific Ocean Perch"
stock.let  = c("POP")
stock.lab  = c("QCS+WCVI+WCHG")
stock.name = c("BC~coast) #c(POP~5ABC+3CD+5DE")
stock.area = c("5ABC+3CD+5DE")
stock.subs = c("5ABC (QCS)", "3CD (WCVI)", "5DE (WCHG)")
Amax       = c(60)
#AnatM      = list(c("est"))
sigmaR     = 0.9
startYear  = 1935; startYearChar = as.character(startYear)
currYear   = 2024; currYearChar  = as.character(currYear)  ## beginning of the year
prevYear   = currYear - 1
nprojYrs   = 10  ## e.g., 10-yr projection
projYear   = currYear + nprojYrs
glist      = list(c("5ABC Trawl Fishery", "3CD Trawl Fishery", "5DE Trawl Fishery",  "QCS Synoptic", "WCVI Synoptic", "WCHG Synoptic", "GIG Historical", "NMFS Triennial", "WCVI Historical"))

## sets of model years for survey abundance indices from series g
Tlist = list(
	list(
	NA, NA, NA,                                          ## No CPUE used for three trawl fisheries
	c(2003:2005,seq(2007,2021,2)),                       ## QCS synoptic
	c(seq(2004,2018,2),2021),                            ## WCVI synoptic
	c(1997,2006:2007,seq(2008,2012,2),seq(2016,2022,2)), ## WCHG synoptic
	c(seq(1967,1973,2),1976:1977,1984,1994),             ## GIG historical
	c(1980,1983,1989,1992,1995,1998,2001),               ## NMFS triennial
	c(1967:1970)                                         ## WCVI historical
	)
)
## sets of model years with proportion-at-age data for series g
Ulist = list(
	list(
	c(1977:2019),                                        ## 5ABC trawl fishery
	c(seq(1980,1984,2),1990:1991,1994:1995,1998:2006,2008,2010:2019), ## 3CD trawl fishery
	c(1978:1980,1982,1984:1995,1997:2007,2009,2013:2017),## 5DE trawl fishery
	c(2003:2005,seq(2007,2021,2)),                       ## QCS synoptic
	c(1996,seq(2004,2018,2),2021:2022),                  ## WCVI synoptic
	c(1997,2006:2007,seq(2008,2012,2),seq(2016,2022,2)), ## WCHG synoptic
	c(1984,1994:1995),                                   ## GIG historical
	c(1989,1992,1995,1998,2001),                         ## NMFS triennial
	NA                                                   ## WCVI historical
	)
)
Tlist        = lapply(1:length(Tlist), function(i){ilst=Tlist[[i]]; names(ilst)=glist[[i]]; return(ilst)})
Ulist        = lapply(1:length(Ulist), function(i){ilst=Ulist[[i]]; names(ilst)=glist[[i]]; return(ilst)})
names(glist) = names(Tlist) = names(Ulist) = stock.lab
if (any(grepl("CPUE",names(Tlist[[1]])))) {
	cpueLim   = range(Tlist[[1]][[grep("CPUE",names(Tlist[[1]]))[1]]])
} else {
	cpueLim   = c(1996,prevYear)
}
texShit      = texThatShit(g=glist, T=Tlist, U=Ulist, Ngear=Ngear, gpad=c(" (commercial data)", " trawl survey series"))  ## g reverse of Awatea (i.e. fisheries then surveys)

run.num      = c(17)
rwt.num      = c(0)
cvpro        = list(rep(0,6))  ## need to be same length as qgees (derived below)
avgCat       = c(1618, 840, 848); names(avgCat) = stock.subs ## areas adjusted for 3C expansion
names(run.num) = names(rwt.num) = names(cvpro) = stock.lab
mcsub        = 1:2000
sigdig       = 3      ## Number of significant digits to output in tables
ptype        = "png"  ## make sure this is the same choice on line 40
##----------------------------
stock.ass  = paste0(spp.name," (", spp.code, ")")
Tmax       = length(startYear:currYear)
ncpue      = sapply(glist,function(x){length(grep("CPUE",x))}) ## number of CPUE series
gsurv=gS   = lapply(glist,function(x){grep("[Ff]isher",x,invert=TRUE)})
gcomm=gC   = lapply(glist,function(x){grep("[Ff]isher",x)})
nsurv      = sapply(gS,length); names(nsurv) = stock.let
ncomm      = sapply(gC,length); names(ncomm) = stock.let

geefun = function(x){
	if (length(x)<=4)
		out = paste0(x, collapse=",")
	else {
		out = texThatVec(x)
		out = gsub("and", ",", gsub("\\s+", "", gsub("-", ",...,", out)))
	}
	return(out)
}
ugees = lapply(1:Nstock, function(i){ (1:length(Ulist[[i]]))[!sapply(Ulist[[i]],function(x){all(is.na(x))})] })
ugees = sapply(ugees,geefun)
qgees = lapply(1:Nstock, function(i){ (1:length(Tlist[[i]]))[!sapply(Tlist[[i]],function(x){all(is.na(x))})] })
cvpro2 = lapply(1:length(cvpro), function(i) {x=cvpro[[i]]; names(x)=qgees[[i]];  return(x)})
qgees = sapply(qgees,geefun)

## Note: gcomm and gsurv below need to be redefined for multiple stock...
## Need something like this : \left\{3_\text{B}\ms{\vee}4_\text{R}\right\}

if (Nstock==1) {
	gsurv.min = min(gsurv[[1]])
	gsurv = sub("-",",...,",texThatVec(gS[[1]]))
	gcomm = sub("-",",...,",texThatVec(gC[[1]]))
	#gcomm = paste0(sort(unique(c(gsurv.max+1, gcomm[[1]]))),collapse=",")
	ugees = ugees[[1]]
	qgees = qgees[[1]]
} else {
	onebs = "\\\\"       ## to escape control characters
	twobs = "\\\\\\\\"   ## to display control characters
	braceL = "twobslefttwobs{"
	braceR = "twobsrighttwobs}"
	msvee  = "twobsmsonebs{twobsvee}"
	unbee  = function(x) {gsub("twobs", twobs, gsub("onebs", onebs, x))}

	smess = paste0(sapply(gsurv,max),"_twobsmathrmonebs{", stock.let, "}")
	smess = paste0(smess,collapse=msvee)
	smess = paste0("1,...,", braceL, smess, braceR)
	smess = unbee(smess)

	imess = paste0(sapply(gsurv,max)+1,"_twobsmathrmonebs{", stock.let, "}")
	imess = paste0(imess,collapse=msvee)
	imess = paste0(braceL, imess, braceR)
	imess = unbee(imess)

	cmess = paste0(sapply(gcomm,max),"_twobsmathrmonebs{", stock.let, "}")
	cmess = paste0(cmess,collapse=msvee)
	cmess = paste0(braceL, cmess, braceR)
	cmess = unbee(cmess)

	gsurv = smess
	gcomm = paste0(imess, ",...,", cmess)

	## Note: want something like this: \mm{\text{B}\left\{1,2\right\}\ms{\vee}\text{R}\left\{1,2,3\right\}}
	umess = paste0("twobsmsonebs{", paste0(paste0("twobsmathrmonebs{",stock.let, "}", braceL, ugees, braceR), collapse=msvee), "}")
	ugees = unbee(umess)
	qmess = paste0("twobsmsonebs{", paste0(paste0("twobsmathrmonebs{",stock.let, "}", braceL, qgees, braceR), collapse=msvee), "}")
	qgees = unbee(qmess)

	nmess = paste0(paste0(nsurv,"_",names(nsurv)), collapse=msvee)
	nsurv = unbee(nmess)
	mmess = paste0(paste0(ncomm,"_",names(ncomm)), collapse=msvee)
	ncomm = unbee(mmess)
}
require(xtable)


medCI = function(x, dig=sigdig, CI=c(0.05,0.95))     # dig is number of dec places, CI = credible interval
{ print(paste0(c(
  prettyNum(round(quantile(x, 0.50), digits=dig), big.mark=","), "~(",
  prettyNum(round(quantile(x, CI[1]), digits=dig), big.mark=","), "-",
  prettyNum(round(quantile(x, CI[2]), digits=dig), big.mark=","), ")"), collapse=""))
}
saveDate = sub("/0","/",sub("^0","",format.Date(Sys.time(),"%m/%d/%Y")))
@
\def\finalYr{\Sexpr{currYear}}%% final year in model
\def\ncomm{\Sexpr{ncomm}}%%      index g for commercial fishery (if more than one, this will need to be revised)
\def\nsurv{\Sexpr{nsurv}}%%      index g for total number of surveys
\def\gsurv{\Sexpr{gsurv}}%%      index g for all surveys
\def\gcomm{\Sexpr{gcomm}}%%      index g for all commercial fisheries
\def\ugees{\Sexpr{ugees}}%%      index g for surveys/fisheries with age data (composition)
\def\qgees{\Sexpr{qgees}}%%      index g for surveys/fisheries with index data (abundance)

\newcommand{\spn}{\Sexpr{spp.name}}
\newcommand{\spc}{\Sexpr{spp.code}}


%###############################################################################
\chapter*{APPENDIX~\thechapter. MODEL EQUATIONS}

\newcommand{\LH}{}%{DRAFT (\Sexpr{saveDate}) not citable}%% Set to {} for final ResDoc
\newcommand{\RH}{}%{CSAP Request ID 225}%% Set to {} for final ResDoc
\newcommand{\LF}{}%{\spn{} 2023}
\newcommand{\RF}{}%{APPENDIX~\thechapter ~-- Model Equations}

\lhead{\LH}\rhead{\RH}\lfoot{\LF}\rfoot{\RF}

%% Revised to reflect the NUTS procedure
\newcommand{\nSims}{\{40,000\,(for base-model)\,| 40,000\,(for area-model)\,| 20,000\,(for sensitivity)\}}%% Total number simulations
\newcommand{\nChains}{8}%% Number of chains
\newcommand{\cSims}{\{5,000\,(base)\,| 5,000\,(area)\,| 2,500\,(sens)\}}%% number of simulations per chain
\newcommand{\cBurn}{\{2,500\,(base)\,| 2,500\,(area)\,| 1,250\,(sens)\}}%% burnin per chain
\newcommand{\cSamps}{\{2,500\,(base)\,| 2,500\,(area)\,| 1,250\,(sens)\}}%% samples retained per chain
\newcommand{\nThin}{\{10\,(base)\,| 10\,(area)\,| 5\,(sens)\}}%% number used for thinning samples
\newcommand{\Nmcmc}{\{20,000\,(base)\,| 20,000\,(area)\,| 10,000\,(sens)\}}%% number of samples per run
\newcommand{\Nbase}{\{20,000\,(base)\,| 20,000\,(area)\,| 10,000\,(sens)\}}%% number of samples per base run/case

%\newcommand{\harvestMax}{0.401}
%\newcommand{\harvestInc}{0.001}
\newcommand{\policyMax}{\{3,500\,t\,(5ABC)\,| 1,250\,t\,(3CD)\,| 1,500\,t\,(5DE)\}}
\newcommand{\policyInc}{various}
\newcommand{\currYear}{\Sexpr{currYear}}%% so can include in captions. 
\newcommand{\prevYear}{\Sexpr{prevYear}}%% so can include in captions. 
\newcommand{\projYear}{\Sexpr{projYear}}%% so can include in captions. 

%%==========================================================
\section{INTRODUCTION}%% CSAP wants this as Heading 2

The 2023 stock assessment of \spn{} (\spc) adopted Stock Synthesis 3 (SS3), version 3.30.20 (\citealt{Methot-etal:2022}, downloaded Jan 30, 2023), which is a statistical age-structured population modelling framework \citep{Methot-Wetzel:2013} that uses \href{https://www.admb-project.org/}{ADMB}'s power for Bayesian estimation of population trajectories and their uncertainties.
The \href{https://vlab.ncep.noaa.gov/web/stock-synthesis/home}{Stock Synthesis Development Team} at NOAA (National Oceanic and Atmospheric Administration, U.S. Dept. Commerce) provides executables and documentation on how to run SS3, and the \href{https://github.com/nmfs-stock-synthesis/stock-synthesis}{SS3 source code} is available on GitHub.

Previously, \spc{} was assessed using a simpler age-structured model called `Awatea', which is a version of Coleraine \citep{Hilborn-etal:2003} that was modified and maintained by Allan Hicks (then at Univ. Washington, now at \href{https://www.iphc.int/}{IPHC}).
Both Awatea and SS3 are platforms for implementing Automatic Differentiation Model Builder software \citep{ADMB:2009}, which provides (a)~maximum posterior density estimates using a function minimiser and automatic differentiation, and (b)~an approximation of the posterior distribution of the parameters using the Markov Chain Monte Carlo (MCMC) method, specifically using the Metropolis algorithm \citep{Gelman-etal:2004}.

SS3 has been used previously in age-structured assessments for \stock{BC stocks} since 2021:
\begin{itemize_csas}{}{}
  \item 2022 -- Canary Rockfish \stock{CAR, BC coast} \citep{Starr-Haigh:2023_car}
  \item 2021 -- Yellowmouth Rockfish \stock{YMR, BC coast} \citep{Starr-Haigh:2022_ymr}
\end{itemize_csas}

Awatea has been used in age-structured assessments for \stock{BC stocks} since 2007:
\begin{itemize_csas}{}{}
  \item 2021 -- Bocaccio \stock{BOR, BC coast} update of 2019 assessment \citep{DFO-SR:2022_bor};
  \item 2020 -- Rougheye/Blackspotted Rockfish complex \stock{REBS, 5DE and 3CD5AB} \citep{Starr-Haigh:2022_rebs};
  \item 2019 -- Bocaccio \stock{BOR, BC coast} \citep{Starr-Haigh:2022_bor};
  \item 2019 -- Widow Rockfish \stock{WWR, BC coast} \citep{Starr-Haigh:2021_wwr};
  \item 2018 -- Redstripe Rockfish \stock{RSR, 5DE and 3CD5ABC} \citep{Starr-Haigh:2021_rsr};
  \item 2017 -- Pacific Ocean Perch \stock{POP, 5ABC} \citep{Haigh-etal:2018_pop5ABC};
  \item 2014 -- Yellowtail Rockfish \stock{YTR, BC coast} \citep{DFO-SAR:2015_ytr};
  \item 2013 -- Silvergray Rockfish \stock{SGR, BC coast} \citep{Starr-etal:2016_sgr};
  \item 2013 -- Rock Sole \stock{ROL, BC coast} \citep{Holt-etal:2016_rol};
  \item 2012 -- Pacific Ocean Perch \stock{POP, 3CD} \citep{Edwards-etal:2014_pop3CD};
  \item 2012 -- Pacific Ocean Perch \stock{POP, 5DE} \citep{Edwards-etal:2014_pop5DE};
  \item 2011 -- Yellowmouth Rockfish \stock{YMR, BC coast} \citep{Edwards-etal:2012_ymr},
  \item 2010 -- Pacific Ocean Perch \stock{POP, 5ABC} \citep{Edwards-etal:2012_pop5ABC};
  \item 2009 -- Canary Rockfish \stock{CAR, BC coast} update of 2007 assessment \citep{DFO-SR:2009_car};
  \item 2007 -- Canary Rockfish \stock{CAR, BC coast} \citep{Stanley-etal:2009_car}.
\end{itemize_csas}

The chief strength of Coleraine|Awatea is the use of a robust likelihood formulation proposed by \citet{Fournier-etal:1998} for the composition data by sex and age (or length).
The robust normal model was used over the more traditional Multinomial error model because it reduced the influence of observations with standardised residuals >\,3 standard deviations \citep{Fournier-etal:1990}.
\citet{Fournier-etal:1990} identified two types of deviations:
%\vspace{-0.75\baselineskip}
\begin{itemize_csas}{}{}
	\item type I -- occasional occurrence of an event of very low probability; and
	\item type II -- probability of observing an event with higher frequency than normal in the population (e.g., school of young fish).
\end{itemize_csas}
Their robustified likelihood function reduces both types of deviations.

SS3 offers two error models: the Multinomial and a compound Dirichlet-Multinomial.
The latter can estimate effective sample sizes that are similar to iterative reweighting methods, but without requiring multiple iterations of running the assessment model \citep{Thorson-etal:2017}.
%%rm: At the time of the stock assessment, SS3 did not offer Fournier's robustified normal likelihood function.

The data inputs to SS3 comprise four files -- \code{`starter.ss'}, \code{`data.ss'}, \code{`control.ss'}, and \code{`forecast.ss'} -- instead of a single file used by Awatea.
Parameter control and priors appear in the \code{control.ss} file, and data appear in the \code{data.ss} file; these two files can be named anything the user wishes because the \code{starter.ss} file specifies their names.
The names for the \code{starter.ss} and \code{forecast.ss} files must remain invariant.
Unlike Awatea, which requires specifying an input file from the command line (e.g. \code{`awatea -ind fielname.txt'}), calling SS3 is done by typing only \code{`ss'} on the command line (assuming \code{`ss.exe'} occurs on the Windows system's \code{PATH}) because the software assumes the presence of the four files listed above.
Additionally, this stock assessment used the safe version of SS3 (\code{`ss\_win.v3.30.20.exe'}, compile date: Sep 30 2022), which performs bound checks, rather than the `optimized' version (\code{`ss\_opt\_win.v3.30.20.exe'}), which is reportedly `fast and optimized for speedy execution'.
(The safe version was renamed to \code{`ss.exe'} for convenience.)
The options in SS3 for fitting the data are more complex than those for Awatea and offer a greater degree of flexibility; however, this flexibility requires a steep learning curve and increases opportunties for inadvertent errors.

The Dirichlet-Multinomial distribution, implemented in SS3 as a model-based method for estimating effective sample size \citep{Thorson-etal:2017} was not used in this assessment for the base run because it was found that model fits were sensitive to the magnitude of sample sizes placed on the AF data (see Appendix E.6.2.3 for details).
In contrast, using the \citet{Francis:2011} mean-age method of reweighting showed no such sensitivity, and estimated credible model fits for the two contrasting sample size options presented.
In past stock assessments for offshore rockfish, the \citet{Francis:2011} mean-age reweighting method was used.
Alternatively, an explicit reweighting using a harmonic mean ratio method based on \citet{McAllister-Ianelli:1997} can be used (e.g., Yellowmouth Rockfish in 2021, \citealt{Starr-Haigh:2022_ymr}).

The running of SS3 was streamlined using custom R code (archived on the GitHub site `\href{https://github.com/pbs-software}{PBS Software}' in the repository `\href{https://github.com/pbs-software/pbs-synth}{\code{PBSsynth}}'), which relied heavily on code provided by the R packages `\href{https://github.com/pbs-software/pbs-awatea}{\code{PBSawatea}}', `\href{https://github.com/r4ss/r4ss}{\code{r4ss}}' \citep{R:2021_r4ss}, and `\href{https://github.com/Cole-Monnahan-NOAA/adnuts}{\code{adnuts}}' \citep{R:2018_adnuts}.
Figures and tables of output were automatically produced in R, an environment for statistical computing and graphics \citep{R:2021_base}. 
The R function \code{Sweave} \citep{Leisch:2002} automatically collated, via \LaTeX, the large amount of figures and tables into \code{`pdf'} files for model runs and \AppRes.

\citet{Methot-Wetzel:2013} provide mathematical notation of equations used in the SS3 model in their \href{https://sedarweb.org/docs/wsupp/S39_RD_08_Methot_and_Wetzel_2013_Fish_Res_App_A.pdf}{Appendix~A}.
Below we present mathematical notation of selected equations used in the SS3 age-structured model (merged with notation used in previous DFO Awatea models), the Bayesian procedure, the reweighting scheme, the prior distributions, and the methods used for calculating reference points and performing projections.

\clearpage
%%==========================================================
\section{MODEL ASSUMPTIONS}

The key model assumptions are:
\begin{enumerate_csas}{}{}
\item The assessed BC population of \Sexpr{stock.ass} comprised \Sexpr{ifelse(Nstock*Narea>1, paste0(switch(Nstock*Narea-1,"two","three","four"), " stocks in PMFC areas ", texThatVec(gsub("\\+",", ",stock.area), simplify=FALSE)), paste0(" a single stock in PMFC areas ", stock.area[1]) )}. Independent regional (area-specific) models were also run for comparison.
\item The \spc{} fishery was dominated by trawl gear ($\sim$99.9\pc{} by catch in the last five years). Annual catches used in the model were taken by `Trawl' fisheries (bottom + midwater gear) in three areas. Negligible catch by other gears (halibut longline, sablefish trap, lingcod \& salmon troll, and rockfish hook \& line) was added to account for total removals. The annual catch was known without error and occurred in the middle of each year.
\item The Beverton-Holt stock-recruitment relationship was time-invariant, with a log-normal error structure.
\item Selectivity was different among fleets (fishery and surveys), and remained invariant over time. Trawl selectivity for the 5ABC fishery (fleet~1) was estimated and trawl selectivities for 3CD (fleet~2) and 5DE (fleet~3) were linked to those from 5ABC. Selectivity parameters for surveys were estimated when ageing data were available (all but WCVI Historical, which was linked to GIG Historical).
\item Mortality (estimated), maturity (fixed), and growth parameters (fixed) were specific to a coastwide population in the multi-area model while these parameters were specific to the populations in the independent regional models.
\item Natural mortality $M$ was estimated using a normal prior, and held invariant over time. This parameter differed between the two sexes.
\item Growth parameters were fixed and invariant over time. These parameters differed between the two sexes.
\item Maturity-at-age for females was fixed and invariant over time.
\item Female fecundity-at-age was directly proportional to female weight-at-age.
\item Recruitment at age~0 was 50\pc{} females and 50\pc{} males.
\item Recruitment standard deviation ($\sigma_R$) was fixed at 0.9.
\item Recruitment settlement distribution among areas was estimated, as were annual deviations (with standard error of annual deviations fixed at 1.0).
\item Only fish ages determined using the preferred otolith break-and-burn methodology \citep{MacLellan:1997} were used because ages determined by surface ageing methods (chiefly before 1978) were biased \citep{Beamish:1979}. Surface ageing was deemed suitable for very young rockfish (ages 1-3).
\item An ageing error (AE) vector based on CVs of observed lengths-at-age was used.
%%\item Commercial samples of catch-at-age in a given 3-month period within a year were representative of the fishery in that quarter if there were $\geq$2 samples in that year.
\item Commercial samples of catch-at-age were representative of the fishery in a given year if there were $\geq$2 samples and $\geq$75 aged otoliths in that year.
\item Relative abundance indices were proportional to the vulnerable biomass at the mid point of the year, after half the catch and half the natural mortality had been removed.
\item The age composition samples came from the middle of the year after half the catch and half the natural mortality had been removed.
\end{enumerate_csas}

\clearpage

%%==========================================================
\section{MODEL NOTATION AND EQUATIONS}

Model notation is given in Table~\AppLet.1, the model equations in Tables \AppLet.2 and \AppLet.3, and description of prior distributions for estimated parameters in Table \AppLet.4. 
The model description is divided into the deterministic components, stochastic components and Bayesian priors. 
Full details of notation and equations are given after the tables. % (in the order of appearance in the tables, as far as is practical). 
Links to model inputs appear in Section~\ref{s:inputs}%% don't need period as Sections contain trailing periods

The deterministic components in Table \AppLet.2 iteratively calculate numbers of fish in each age class (and of each sex) through time, while allowing for the commercial catch data, weight-at-age and maturity data, and known fixed values for all parameters.

%%\newpage
Parameters not assumed to be fixed were estimated in the context of recruitment stochasticity.
This is accomplished by the stochastic components given in Table \AppLet.3. 

Incorporation of the prior distributions for estimated parameters is necessary for a full Bayesian implementation, the goal of which is to minimise the objective function $\Fobj(\bfTh)$ given by \eref{Fobj}. 
This function is derived from sum of the negative log likelihoods from the the deterministic, stochastic and prior components of the model.

%%\newpage
%%\medskip

% ********************** Table 1 ************************************
\subsection{Model notation}

% \baselineskip 2.5ex \vspace{-2ex}
\setlength\tabcolsep{0pt}

%% The following is too harsh:
%\fontdimen14\textfont2=6pt
%\fontdimen15\textfont2=6pt
%\fontdimen16\textfont2=5pt
%\fontdimen17\textfont2=5pt

\begin{longtable}{L{1.00in}L{5.5in}}
\caption{Notation for the SS3 catch-at-age model (continued overleaf). The assessment model uses only `cohorts' (age-classes by year) even though SS3 recognises finer subdivisions of time called `morphs' (seasons), which can be further characterised by `platoons' (rates of growth). }%
%% Note: $\mr{\Sexpr{stock.let[1]}}$ denotes `\Sexpr{stock.lab[1]}'.}%
\label{tab:notate}
\\ \hline\\[-2.2ex]
{\bf Symbol}   & \multicolumn{1}{c}{{\bf Description and units}} \\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
{\bf Symbol}   & \multicolumn{1}{c}{{\bf Description and units}} \\[0.2ex]\hline\\[-1.5ex] \endhead
\hline\\[-2.2ex]   \endfoot  \hline \endlastfoot  %
& \multicolumn{1}{c}{\bf{Indices (all subscripts)}} \\[0.5ex]
$a$            & \mbull age class, where $a = 1, 2, 3,... A$, and\\
               & \nbull $a^\prime$ = reference age near youngest age well-represented in data;\\
               & \nbull $a^{\dprime}$ = reference age near oldest age well-represented in data\\
$l$            & \mbull length bin, where $l = 1, 2, 3,... \Lambda$, and $\Lambda$ is the bin index of the largest length;\\
               & \nbull $L^\prime$ = reference length for $a^{\prime}$;\\
               & \nbull $L^{\dprime}$ = reference length for $a^{\dprime}$;\\
               & \nbull $\breve{L}_l, \, \mathring{L}_l$ = minimum and middle length of length bin $l$, respectively\\
$t$            & \mbull model year, where $t = 1, 2, 3,... T$, corresponds to actual years:\\
               & \Sexpr{startYear}, ..., \Sexpr{currYear}, and $t=0$ represents unfished equilibrium conditions\\
$g$            & \mbull index for series (abundance|composition) data:\\
  \Sexpr{paste0(texShit$gtab,collapse="")}
$s$            & \mbull sex, $1{=}$females, $2{=}$males\\

\pagebreak%[-1.5ex]

 & \multicolumn{1}{c}{\bf{Index ranges}} \\
$A$            & \mbull accumulator age-class, $A\elof{\Sexpr{paste0(Amax,collapse=",")}}$\\
$G$            & \mbull number of fleets (fisheries and surveys)\\
$\Lambda$      & \mbull number of length bins\\
$T$            & \mbull number of model years, $T=\Sexpr{Tmax}$\\
${\bf T}_g$    & \mbull sets of model years for survey abundance indices from series $g$, listed here %\\
   for clarity as actual years (subtract \Sexpr{startYear-1} to give model year $t$):\\
  \Sexpr{paste0(texShit$ttab,collapse="")}
${\bf U}_g$    & \mbull sets of model years with proportion-at-age data for series $g$:\\% (listed here as actual years):\\
  \Sexpr{paste0(texShit$utab,collapse="")}
\\[-1ex]

%\pagebreak

& \multicolumn{1}{c}{{\bf Data and fixed parameters}} \\[0.5ex]
$\widetilde{a}_{a}$   & \mbull age after bias adjustment for age $a$ (used in ageing error)\\
$\xi_{a}$             & \mbull standard deviation for age $a$ (used in ageing error)\\
$p_{\ds atgs}$        & \mbull observed weighted proportion of fish from series $g$ in each year $t \in {\bf U}_g$ that are
                        age-class $a$ and sex $s$; so $\Sigma_{a=1}^{A} \Sigma_{s=1}^2 p_{atgs} = 1$ for each $t  \in {\bf U}_g$\\%; in SS3:\\%%, $g=\ugees$\\
%                      & \nbull $p_l$\,= observed proportion in length bin\,$l$;\\
%                      & \nbull $p_a$\,= observed proportion in age\,$a$\\%; and\\
%                      & \nbull $p_z$\,= observed proportion by size in length bin\,$l$;\\
%                      & \nbull the \spc{} stock assessment only used $p_a$\\
% $\tau_{tg}$         & \mbull inverse of assumed sample size that yields corresponding $p_{atgs}$\\
$n_{tg}$              & \mbull specified sample size that yields corresponding $p_{atgs}$\\
$\widetilde{n}_{tg}$  & \nbull effective sample size based on $\widehat{p}_{atgs}$\\
$m_a$                 & \mbull proportion of age-class $a$ females that are mature, fixed from data\\
$w_{as}$              & \mbull average weight (kg) of individual of age-class $a$ of sex $s$ from fixed parameters\\ 
($\widebar{w}_{tg}$, $\psi_{tg}$, $\psi_{tg}^\prime$)  & \mbull mean body weight (kg) by year ($t$) and fleet ($g$); SD $\widebar{w}_{tg}$; SD offset to $\psi_{tg}$\\ 
%$\widebar{w}_{tg}$    & \mbull mean body weight (kg) by year ($t$) and fleet ($g$)\\ 
%$\psi_{tg}$           & \mbull standard deviation of $\widebar{w}_{tg}$\\
%$\psi_{tg}^\prime$    & \mbull user-specified standard deviation offset to add to $\psi_{tg}$\\
($C_{tg}$, $\tau_{tg}$) & \mbull observed catch biomass (tonnes) in year $t$=1 to $T\minus\text{1}$ for fleet $g$; SD $C_{tgs}$\\
%$\tau_{tg}$           & \mbull standard deviation of $C_{tgs}$\\
($d_{tg}$, $\delta_{tg}$, $\delta_{tg}^\prime$)  & \mbull discarded catch biomass (tonnes) in year $t$ for fleet $g$; SD $d_{tg}$; SD offset to $\delta_{tg}$\\
%$\delta_{tg}$         & \mbull standard deviation of $d_{tg}$\\
%$\delta_{tg}^\prime$  & \mbull user-specified standard deviation offset to add to $\delta_{tg}$\\
($I_{tg}$, $\kappa_{tg}$, $\kappa_{tg}^\prime$)  & \mbull biomass indices from surveys $g = \gsurv$, for year $t \in {\bf T}_g$; SD $I_{tg}$; SD offset to $\kappa_{tg}$\\
%$I_{tg}$              & \mbull biomass estimates (tonnes) from surveys $g = \gsurv$, for year $t \in {\bf T}_g$, tonnes\\
%$\kappa_{tg}$         & \mbull standard deviation of $I_{tg}$\\
%$\kappa_{tg}^\prime$  & \mbull user-specified standard deviation offset added to $\kappa_{tg}$\\
% **$f_{1t}, f_{2t}$  & *needed?, what's the assumption? fraction of catch taken prior to research and charter vessel surveys  \\
$\sigma_R$            & \mbull standard deviation parameter for recruitment process error, $\sigma_R = \Sexpr{sigmaR}$\\
$\epsilon_t$          & \mbull recruitment deviations arising from process error, where $\epsilon_t \sim \Norm(0, \sigma_R^2)$\\
$b_t$                 & \mbull recruitment bias adjustment, modulates recruitment variance over time: $b_t\sigma_R^2$\\
                      & \nbull ranges from 1 (data-rich years) to 0 (data-poor years)\\
% $v_{gR}$            & variance parameter for right limb of selectivity curve for series $g = 1,...,7$; $v_{gR} = 100$\\
% $v_{R}$             & variance parameter for right limb of selectivity curves, $v_{R} = e^{100}$\\
% & ~~fixed at 100 to give no descending limb
$\widehat{x}$       & \mbull estimated values of observed data $x$ (generalised)\\
\\[-.5ex]

& \multicolumn{1}{c}{{\bf Estimated parameters}} \\[0.5ex]
$\bfTh$                & \mbull set of estimated parameters:\\
$R_0$                  & \mbull virgin recruitment of age-0 fish (numbers of fish, 1000s)\\
%$\mathring{p}_{\alpha}$ & \mbull proportion recruitment (in natural log space) allocated to subarea $\alpha$\\
%$\nu_{t,\alpha}$       & \mbull standard deviation to add to $\mathring{p}_{\alpha}$ in year $t$\\
($\mathring{p}_{\alpha}$, $\nu_{t,\alpha}$, $\zeta_{\alpha}$) & \mbull log proportion recruitment allocated to subarea $\alpha$; SD added to $\mathring{p}_{\alpha}$; SE of $\nu_{t,\alpha}$\\
$M_{s}$                & \mbull natural mortality rate for sex $s = 1,2$\\
$h$                    & \mbull steepness parameter for Beverton-Holt recruitment\\
$q_g$                  & \mbull catchability for fleets ($g=\qgees$)\\ 
%%$\mu_g$              & \mbull age of full selectivity for females ($g=\ugees$)\\
%%$v_{\mr{L}g}$        & \mbull log parameter for width of ascending limb of selectivity curve\\
%%$v_{\mr{R}g}$        & \mbull log parameter for width of descending limb of selectivity curve\\
$\beta_{itg}$          & \mbull double-normal parameters for females ($s=1$), 
                      where $i{=}1,...,6$ for the six $\beta$ parameters that determine selectivity $S_{atgs}$ for
                      year $t$ and series $g{=}\ugees$, using
                      joiner functions $j_{1atgs}$ and $j_{2atgs}$ for ascending- and descending-limb
                      functions $\pi_{1atgs}$ and $\pi_{2atgs}$, respectively, where $\gamma_{1tgs}$ and $\gamma_{2tgs}$ describe exponential terms\\
$\Delta_{itg}$      & \mbull shift in vulnerability for males ($s=2$), where $i{=}1,...,5$ for the five $\Delta$ parameters and subscripts $tg$ are the same as those for $\beta$\\
% $v_{gL}, v_{gR}$  & \mbull variance parameters for left and right limbs of selectivity for series $g = 1,...,7$; $v_{gR}= 100$ fixed to give no descending limb\\
% $\sigma_I$        & \mbull standard deviation parameter for initial age structure error \\
% **$\tau_2$        & \mbull standard deviation of age proportion measurement error \\
% **$\kappa^2$      & \mbull combined variance $\sigma_1^2 + \tau_1^2$ \\
% **$\rho$          & \mbull variance ratio $\sigma_1^2 / \kappa^2$, fixed in the model analysis \\
%%$\alpha$, $\beta$ & \mbull alternative formulation of recruitment:\\
%%                  & \nbull $\alpha = (1 - h) B_0 / (4 h R_0)$ and $\beta = (5 h - 1) / 4 h R_0$;\\ 
% $\widehat{\cdot}$ & \mbull estimated value of observed data represented by $\cdot$
\\[-.5ex]

%\pagebreak

& \multicolumn{1}{c}{{\bf Derived states}} \\[0.5ex]
$N_{ats}$           & \mbull number of age-class $a$ fish (1000s) of sex $s$ at the start of year $t$\\
$B_t$               & \mbull spawning biomass (tonnes mature females) at the start of year $t$\\
$B_0$               & \mbull virgin spawning biomass (tonnes mature females) at the start of year $0$\\
$R_t$               & \mbull recruitment of age-0 fish (numbers of fish, 1000s) in year $t$\\
$\rho_t$            & \nbull recruitment deviations (log thousands age-0 fish) in year $t$\\
$V_{tg}$            & \mbull vulnerable biomass (tonnes, females + males) in the middle of year $t$\\
$\Biom_{tg}$        & \mbull mid-season retained dead biomass (tonnes, females + males)\\
$F_{tg}$            & \mbull instantaneous fishing mortality rate for time period $t$ by fishery $g$\\
                    & \nbull hybrid method uses Pope's approximation and Baranov's equation\\
                    & \nbull calculations facilitated by temporary variables $\Temp_{tg}$ and joiners $\Joyn_{tg}$\\
$Z_{ats}$           & \mbull total mortality rate (natural \& fishing) for time period $t$ and sex $s$\\

\\[-0.5ex]
& \multicolumn{1}{c}{{\bf Log-likelihood components}} \\[0.5ex]
$\Lagr_{1g}(\bfTh | \{ \widehat{I}_{tg} \} )$ & \mbull CPUE or abundance index\\
$\Lagr_{2g}(\bfTh | \{ d_{tg} \} )$           & \mbull discard biomass\\
$\Lagr_{3g}(\bfTh | \{ \widebar{w}_{tg} \} )$ & \mbull mean body weight\\
$\Lagr_{4g}(\bfTh | \{ l_{tg} \} )$           & \mbull length composition\\
$\Lagr_{5g}(\bfTh | \{ a_{tg} \} )$           & \mbull age composition\\
$\Lagr_{6g}(\bfTh | \{ z_{tg} \} )$           & \mbull generalised size composition\\
$\Lagr_{7g}(\bfTh | \{ C_{tg} \} )$           & \mbull initial equilibrium catch\\
$\Lagr_{R}(\bfTh | \{ R_{tg} \} )$            & \mbull recruitment deviations\\
$\Lagr_{\phi_j}(\bfTh | \{ \phi_j \} )$       & \mbull parameter priors\\
$\Lagr_{P_t}(\bfTh | \{ P_t \} )$             & \mbull random parameter deviations (if time-varying)\\
$\Lagr(\bfTh)$                                & \mbull total log-likelihood \\
\\[-.5ex]

& \multicolumn{1}{c}{{\bf Prior distributions and objective function}} \\[0.5ex]
$\phi_j(\bfTh)$          & \mbull prior distribution for parameter $j$ \\
$\phi(\bfTh)$            & \mbull joint prior distribution for all estimated parameters\\
$\Fobj(\bfTh)$     & \mbull objective function to be minimised\\
\hline
%\end{tabular} \newp % \baselineskip \mybaselineskip
%\end{table}
\end{longtable}
\newpage


% ********************** Table 2 ************************************
\subsection{Deterministic components}

\def\beq{ \begin{fleqn} \begin{equation}}
\def\eeq{\end{equation} \end{fleqn} }
\def\bec{\\[-30pt]\begin{center}}%%\hspace{-15ex}}
\def\eec{\end{center} \\[-12pt]}%% \vspace{-1ex}}

\leftskip=0em%   1.5em   %indents caption (that isn't done as a caption)
\parindent=0em% -1.5em  % then revert back afterwards

\begin{longtable}{L{6.5in}}
\caption{Deterministic components. Using the catch, weight-at-age and maturity data, with fixed values for all parameters, the initial conditions are calculated from \eref{Na0s}-\eref{LA0s}, and then state dynamics are iteratively calculated through time using the main equations \eref{Nats}, selectivity functions \eref{Satgs}-\eref{gammas}, and the derived states \eref{Lats}-\eref{Rt}. Estimated observations for survey biomass indices and proportions-at-age can then be calculated using \eref{Itg.hat} and \eref{patgs.hat}. In Table~\ref{tab:stocomp}, the estimated observations of these are compared to data.}
\label{tab:detcomp}
\\ \hline\\[-2.2ex]

%\multicolumn{1}{c}{\textbf{Deterministic components}} \\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
%\multicolumn{1}{c}{\textbf{Deterministic components}} \\[0.2ex]\hline\\[-1.5ex] \endhead
%\hline\\[-2.2ex]   \endfoot \\ \hline \endlastfoot  %

%% (RH 210511) \vspace appears to be incompatible with longtable
%% (RH 210512) \multicolumn does not work after a call to fleqn 
%% (RH 210513) longtable does not recognise pagebreaks once equation has been issued but:
%% (RH 210513) \pagebreak does work in longtable if equations are properly returned using '\\'
%% (RH 220718) Why are equation labels in caption not updating? Perhaps update to amsmath has changed labelling. See Werner at:
%% https://tex.stackexchange.com/questions/210390/why-does-label-not-work-in-math-mode-when-using-fleqn-with-amsmath

%%----------------------------------------------------------
\bec {\bf Initial conditions (${\bf \bft \bfeq 0 \,;\, \bfmi{s} \bfeq 1,2}$\,)} \eec
%%\multicolumn{1}{c}{\bf Initial conditions (${\bf \bft \bfeq 0 \,;\, \bfmi{s} \bfeq 1,2}$\,)} \\[-0.5ex]

\beq \elabel{Na0s}
  N_{a0s} = 0.5 R_0 e^{\minus aM_{s}}~;~~~  0 \leq a \leq 3A \minus 1
  \eeq \\

\beq \elabel{NA0s}
  N_{A0s} = \sum\nolimits_{a=A}^{3A\minus1} N_{a0s} + (N_{3A \minus 1,0s} \, e^{\minus M_{as}}) \, / \,(1-e^{\minus M_{as}})
  \eeq \\

\beq \elabel{B0} 
  B_0 = B_1 = \sum\nolimits_{a=0}^A f_{as} N_{a0s}~;~~~\mr{where}~~~f_{as}=w_{as} m_{as} o_{as};~~~ s{=}1~\mr{(female)}% \text{\footnotesize ~~***** need to check equation}
  %B_0 = B_1 = \sum\nolimits_{a=0}^A w_{as} m_{a} N_{a0s}~;~~~ s{=}1~~\mr{(female)}% \text{\footnotesize ~~***** need to check equation}
  \eeq \\

\begin{fleqn}     % \beq puts -ve vspace, not good for { ...
\begin{equation}
\elabel{La0s}
L_{a0s} = \left\{
  \begin{array}{ll}
    \breve{L}_1 + ( \, a / a^\prime \, ) \, ( \, L_{s}^{\prime} - \breve{L}_1 \, )  & ;~~a \leq a^{\prime}\\
    L_{\infty s} + ( \, L_{s}^{\prime} - L_{\infty s} \, ) \, e^{\minus k_s ( a \minus a^{\prime} ) }  & ;~~a^{\prime} < a \leq A \minus 1
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

\beq \elabel{Linf}
  \mr{~~~~~~~~~~~~~~where~~} L_{\infty s} = L_{s}^{\prime} + ( L_{s}^{\dprime} - L_{s}^{\prime} ) \, \left[ 1 - e^{\minus k_s ( a^{\dprime} \minus a^{\prime} ) } \right]
  \eeq \\%% final return '\\' is necessary

\beq \elabel{LA0s}
  L_{A0s} = \frac { \sum\nolimits_{a=A}^{2A} \left[ e^{\minus 0.2 (a \minus A \minus 1 ) } \right] \left[ L_{As} + ( a / A - 1) ( L_{\infty s} - L_{A0s} ) \right] }{ \sum\nolimits_{a=A}^{2A} e^{\minus 0.2 (a \minus A \minus 1) } }
  \eeq \\

%%----------------------------------------------------------
\\[-0.5ex]
\bec {\bf State dynamics (${\bf 2 \bfleq \bft \bfleq \bfT \,;\, \bfmi{s} \bfeq 1,2}$\,)} \eec

\begin{fleqn}
\begin{equation}
\elabel{Nats}
N_{ats} = \left\{
 \begin{array}{ll}
 c R_{0t}  & ;~~a = 0, c = \text{\footnotesize proportion female}\\
 N_{a \minus 1, t \minus 1, s} \, e^{\minus Z_{a,t \minus 1,s}}  & ;~~1 \leq a \leq A \minus 1\\
 N_{A \minus 1, t \minus 1, s} \, e^{\minus Z_{A \minus 1, t \minus 1, s}} + N_{A, t \minus 1, s} \, e^{\minus Z_{A, t \minus 1, s}}  & ;~~a = A
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

%% \pagebreak does not work in longtable if equations are not properly returned using '\\' (RH 210513)
%%\pagebreak

%%----------------------------------------------------------
\\[-0.5ex]
\bec {\bf Selectivity pattern 20 ($\bfmi{g} \bf = \Sexpr{ugees}$)} \eec 

\beq \elabel{Satgs}
  S_{atgs} = \pi_{\ds 1atgs} ( 1 - j_{\ds 1atgs} ) + j_{\ds 1atgs} \left[ ( 1 - j_{\ds 2atgs} ) + j_{\ds 2atgs} \pi_{\ds 2atgs} \right]
  \eeq \\

\beq \elabel{j1atgs}
  j_{\ds 1atgs} = 1 \, / \, \left[ 1 + e^{\minus 20 ( a \minus \beta_{1tgs} ) / (1 + \left| a \minus \beta_{1tgs} \right| ) } \right]~;~~~ \beta_{1tgs} = \text{\footnotesize first age when~} S_{tgs}{=}1
  \eeq \\

\beq \elabel{j2atgs} 
  j_{\ds 2atgs} = 1 \, / \, \left[ 1 + e^{\minus 20 ( a \minus a_{tgs}^{\star} ) / (1 + \left| a \minus a_{tgs}^{\star} \right| ) } \right]~;~~~ a_{tgs}^{\star} = \text{\footnotesize last age when~} S_{tgs}{=}1
  \eeq \\

\beq \elabel{astar}
  a_{\ds tgs}^{\star} = \beta_{1tgs} + ( 0.99 A - \beta_{1tgs} ) / ( 1 + \beta_{2tgs} )~;~~~ \text{\footnotesize assuming age bin = 1y}
  \eeq \\

\beq \elabel{pi1atgs}
  \pi_{\ds 1atgs} = \left( \frac { 1 }{ 1 + e^{\minus \beta_{5tgs}} } \right) \left( \frac { 1 }{ 1 - ( 1 + e^{\minus \beta_{5tgs}} ) } \right) \left( \frac{ e^{\minus ( a \minus \beta_{1tgs} )^2 /  e^{\beta_{3tgs}} } - \gamma_{1tgs} }{ 1 - \gamma_{1tgs} } \right)
  \eeq \\

\beq \elabel{pi2atgs}
  \pi_{\ds 2atgs} = 1 + \left[ \left( \frac { 1 }{ 1 + e^{\minus \beta_{6tgs}} } \right) - 1 \right] \left( \frac{ e^{\minus ( a \minus a_{tgs}^{\star} ) /  e^{\beta_{4tgs}} } - 1 }{ \gamma_{2tgs} - 1 } \right)
  \eeq \\

\beq \elabel{gammas}
  \gamma_{1tgs} = e^{ \minus (1 \minus \beta_{1tgs})^2 / e^{\beta_{3tgs}} }~;~~~ \gamma_{2tgs} = e^{ \minus (A \minus a_{tgs}^{\star} )^2 / e^{\beta_{4tgs}} }
  \eeq \\

%%----------------------------------------------------------
\pagebreak
\\[-2.5ex]
\bec {\bf Derived states ($\bf 1 \bfleq \bft \bfleq \bfT - 1$\,)} \eec

\beq \elabel{Lats}
  L_{ats} = L_{a\minus1,t\minus1,s} + \, ( \, L_{a\minus1 \minus k,t\minus1,s} - L_{\infty s} \, ) \, ( \, e^{\minus k_s} - 1 \, );~~~ a < A 
  \eeq \\

\beq \elabel{LAts}
  L_{Ats} = \frac { N_{A\minus1,ts} \widebar{L}_{Ats} + N_{Ats} \, \left[ \, L_{Ats} - ( \, L_{Ats} + L_{\infty s} \, ) \, ( \, e^{\minus k_s} - 1 \, ) \right] }{ N_{A\minus1,ts} + N_{Ats} }
  \eeq \\

\beq \elabel{Lats.bar}
  \widebar{L}_{ats} = {L}_{ats} + ( \, {L}_{ats} - L_{\infty s} \, ) \, ( \, e^{\minus 0.5 k_{s}} - 1 \, )
  \eeq \\

\begin{fleqn}
\begin{equation}
\elabel{cvage}
\alpha_{ats} = \left\{
 \begin{array}{ll}
 \widebar{L}_{ats} \nu_{s}^{\prime} \, | \, a_{ts} \nu_{s}^{\prime}  & ;~~a \leq a^{\prime}\\
 \widebar{L}_{ats} \left[ \nu_{s}^{\prime} + ( \widebar{L}_{ats} \minus L_{s}^{\prime} ) / ( L_{s}^{\dprime} \minus L_{s}^{\prime} ) ( \nu_{s}^{\dprime} \minus \nu_{s}^{\prime} ) \right] \, | &\\
  ~~~a_{ts} \nu_{s}^{\prime} \left[ \nu_{s}^{\prime} + ( a_{ts} \minus a_{s}^{\prime} ) / ( a_{s}^{\dprime} \minus a_{s}^{\prime} ) ( \nu_{s}^{\dprime} \minus \nu_{s}^{\prime} ) \right]  & ;~~a^{\prime} < a < a^{\dprime}\\
 \widebar{L}_{ats} \nu_{s}^{\dprime} \, | \, a_{ts} \nu_{s}^{\dprime}  & ;~~a^{\dprime} \leq a
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

\begin{fleqn}
\begin{equation}
\elabel{len.age}
\varphi_{\ds lats} = \left\{
 \begin{array}{ll}
 \Phi \left[ (\breve{L}_{l} - \widebar{L}_{ats} ) / \alpha_{ats} \right]  & ;~~l = 1\\
 \Phi \left[ (\breve{L}_{l+1} - \widebar{L}_{ats} ) / \alpha_{ats} \right] - \Phi \left[ (\breve{L}_{l} - \widebar{L}_{ats} ) / \alpha_{ats} \right]  & ;~~1 < l < L\\
 1 - \Phi \left[ (\breve{L}_{l} - \widebar{L}_{ats} ) / \alpha_{ats} \right]  & ;~~l = L
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

\beq \elabel{wls} 
  w_{\ds ls} = a_s \, \mathring{L}_{\, l}^{\, b_s}~;~~~ \mathring{L}_{\, l} = \text{\footnotesize mid-size of length bin}~l
  \eeq \\

\beq \elabel{fa} 
  f_a = \sum\nolimits_{l=1}^{\Lambda} \, \varphi_{\ds las} \, m_{\ds l} o_{\ds l} w_{\ds ls}~;~~~ s{=}1, m{=}\text{\footnotesize maturity}, o{=}\text{\footnotesize eggs/kg}
  \eeq \\

\beq \elabel{Zats}
  Z_{ats} = M_{as} \sum\nolimits_{g \in \Sexpr{gcomm}} \, ( \, S_{atgs} \, F_{tg} \, )~;~~~ F_{tg} = \text{\footnotesize apical fishing mortality rate}
  \eeq \\

\beq \elabel{Tj1T}
  \Temp_{1tg} = C_{tg}  / ( \widehat{\Biom}_{tg} + 0.1 C_{tg} )~;~~ \Joyn_{1tg} = 1 / \left[ 1 + e^{30 ( \Temp_{1tg} \minus 0.95 ) } \right]~;~~ \Temp_{2tg} = \Joyn_{1tg} \Temp_{1tg} + 0.95 ( 1 - \Joyn_{1tg} )
  \eeq \\

\beq \elabel{F1tg}
  F_{1tg} = -\log \, ( \, 1 - \Temp_{2tg} )
  \eeq \\

\beq \elabel{Ct.hat}
  \widehat{C}_t = \sum\nolimits_{g\in\Sexpr{gcomm}} \sum\nolimits_{s=1}^2 \sum\nolimits_{a=0}^{A} \, \frac{ F_{1tg} }{ Z_{ats} } \, w_{as} N_{ats} S_{atgs} \lambda_{ats}~;~~~ \lambda_{ats} = ( \, 1 - e^{\minus Z_{ats}} ) / ( \, Z_{ats} \, )
  \eeq \\

\beq \elabel{Zt.adj}
  \adj{Z}_{t} = C_{t} / ( \widehat{C}_t + 0.0001 )~;~~ Z_{ats}^\prime = M_{as} + \adj{Z}_{t} ( Z_{ats} - M_{as} )~;~~ \lambda_{ats}^\prime = ( 1 - e^{\minus Z_{ats}^\prime} ) / ( Z_{ats}^\prime )
  \eeq \\

\beq \elabel{T3tg}
  \Temp_{3tg} = \sum\nolimits_{s=1}^{2} \sum\nolimits_{a=0}^{A} w_{as} N_{ats} S_{atgs} \lambda_{ats}^\prime
  \eeq \\

\beq \elabel{F2tg}
  F_{2tg} = C_{tg} / ( \Temp_{3tg} + 0.0001 )~;~~~ \Joyn_{2tg} = 1 / \left[ 1 + e^{30(F_{2tg} \minus 0.95 F_{\mr{max}} ) } \right]
  \eeq \\

\beq \elabel{Ftg}
  F_{tg} = \Joyn_{2tg} F_{2tg} + ( 1 - \Joyn_{2tg} ) F_{\mr{max}}~;~~~ \text{\footnotesize updated estimate of~} F \text{\footnotesize ~using hybrid method above}
  \eeq \\

\beq \elabel{Cats}
  C_{ats} = \sum\nolimits_{g\in\Sexpr{gcomm}}  \, \frac{ F_{tg} }{ Z_{ats}^\prime } \, w_{as} N_{ats} S_{atgs} \lambda_{ats}^\prime
  \eeq \\

\beq \elabel{Bt}
  B_{t} = \sum\nolimits_{a=0}^{A} \, N_{ats} f_{a}~;~~~s{=}1, f{=} \text{\footnotesize fecundity}
  \eeq \\

\beq \elabel{Vtg}
  V_{tg} = \sum_{s=1}^2 \sum_{a=1}^A e^{\minus M_{s}/2}\, w_{as} \, N_{ats} \, S_{atgs}~;~~~ g \in \{\gcomm\}, \,\, u_{tg} =  C_{tg}  / V_{tg}, \,\, u_{atgs} = u_{tg} S_{atgs}
  \eeq \\

\beq \elabel{Rt}
  R_t = \frac{ 4 h R_0 B_{t\minus 1} }{ (1-h) B_0 + (5 h - 1) B_{t\minus 1} } ~~\left( \equiv  \frac{B_{t\minus 1}}{\alpha + \beta B_{t\minus 1}} \right)
  \eeq \\

\pagebreak
\\[-2.5ex]
\bec {\bf Ageing error} \eec
%%$\widetilde{a}$     & adjusted ages after ageing error is applied to a modeled distribution of true ages\\
%% Jon Schnute:
\beq \elabel{cdn.fun}
  \Phi(x|\mu,\sigma) = \frac{1}{\sqrt{2\pi}} \int_{\minus\infty}^{(x-\mu)/\sigma} e^{\minus (t^2 / 2)}\,dt~~~\text{\footnotesize cumulative normal distribution}
  \eeq \\
%%\beq \widetilde{\Norm}(\mu,\sigma) = \frac{1}{2} \left[ 1 + \Xi \left( \frac{x - \mu}{\sigma \sqrt{2}} \right) \right];~~~ \text{\footnotesize where~~~} \Xi(x) = \frac{1}{\sqrt{2\pi}} \int_{\minus\infty}^{x} e^{\minus t^2}\,dt
%%  \label{cdn.fun} \eeq \\

\begin{fleqn}
\begin{equation}
\elabel{age.err}
\Psi_{a} = \left\{
 \begin{array}{ll}
 \Phi \left( \frac{ a - \widetilde{a}_{a} }{ \xi_{a} } \right)  & ;~~a = 1\\
 \Phi \left( \frac{ a + 1 - \widetilde{a}_{a} }{ \xi_{a} } \right) - \Phi \left( \frac{ a - \widetilde{a}_{a} }{ \xi_{a} } \right)  & ;~~1 < a < A\\
 1 - \Phi \left( \frac{ A - \widetilde{a}_{a} }{ \xi_{a} } \right)  & ;~~a = A
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

%%   for (a=0; a<=nages;a++)
%%    {
%%     age = age_err(Keynum,1,a); // bias-adjusted age?
%%     for (b=2;b<=n_abins;b++)     //  so the lower tail is accumulated into the first age' bin
%%       age_age(Keynum,b,a)= cumd_norm((age_bins(b)-age)/age_err(Keynum,2,a));
%%
%%     for (b=1;b<=n_abins-1;b++)
%%       age_age(Keynum,b,a) = age_age(Keynum,b+1,a)-age_age(Keynum,b,a);
%%
%%     age_age(Keynum,n_abins,a) = 1.-age_age(Keynum,n_abins,a) ;     // so remainder is accumulated into the last age' bin

\\[-1ex]
\bec {\bf Estimated observations} \eec
%%  ($\bf 1 \bfleq \bft \bfleq \bfT$\,)} \eec

\beq \elabel{Itg.hat}
  \widehat{I}_{tg} = q_g  \sum_{s=1}^2 \sum_{a=1}^A e^{-M_{s}/2} (1 - u_{ats}/2)  w_{as} S_{ags} N_{ats} \,; \ \ \ t \in {\bf T}_g, ~g=\qgees
  \eeq \\

\beq \elabel{patgs.hat}
  \widehat{p}_{atgs} = \frac{e^{-M_{s}/2} (1 - u_{ats}/2) S_{ags} N_{ats}}{\sum_{s=1}^2 \sum_{a=1}^A e^{-M_{s}/2} (1 - u_{ats}/2) S_{ags} N_{ats}}; \ \mm{1 \leq a \leq A,~ t \in {\bf U}_g,~g=\ugees,~s=1,2}
  \eeq \\

%\noindent \hrule %\tabline
%\\ \hline\\[-2.2ex]
\\[0ex]\hline

\end{longtable}
\clearpage

% ********************** Table 3 ************************************
\subsection{Stochastic components}

\begin{longtable}{L{6.5in}}
\caption{Stochastic components. Calculation of likelihood function $\Lagr(\bfTh)$ for stochastic components of the model in Table~\ref{tab:detcomp}, and resulting objective function $f(\bfTh)$ to be minimised.}
\label{tab:stocomp}
\\ \hline\\[-2.2ex]

%\multicolumn{1}{c}{\textbf{Stochastic components}} \\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
%\multicolumn{1}{c}{\textbf{Stochastic components}} \\[0.2ex]\hline\\[-1.5ex] \endhead
%\hline\\[-2.2ex]   \endfoot \hline \endlastfoot  %

\bec {\bf Estimated parameters} \eec

%% \beq \bfTh = \left( { \vrule height 2.5ex width 0ex} \{\mu_g\}, \{v_{gL}\}, \{\Delta_g\}, \{q_g\}, \{M_s\}, R_0, h \right)
%% \beq \bfTh = \left\{ \mu_1, \mu_2, \mu_6, v_{1L}, v_{2L}, v_{6L}, \Delta_1, \Delta_2, \Delta_6, q_1, q_2, q_3, M_1, M_2, R_0, h \right\}
%% redoing in order that output is in:
%%\beq \bfTh = \left\{ R_0; M_{1,2}; h; q_{\qgees}; \mu_{\ugees}; \Delta_{\ugees}; v_{\ugees L} \right\} \label{lpar} \eeq 

\beq \elabel{bfTh}
  \bfTh = \left\{ R_0; M_{1,2}; h; q_{\qgees}; \mu_{\ugees}, \pi_{\mr{T}\ugees}, v_{\mr{L}\ugees L}, v_{\mr{R}\ugees}, \pi_{\mr{F}\ugees}, \theta_{\ugees} \right\}
  \eeq 

\bec {\bf Recruitment deviations} \eec 

\beq \elabel{rdevs}
  \rho_{t+1} = \log R_{t+1}  - \log B_{t} + \log(\alpha + \beta B_{t}) + 0.5 b_{t} \sigma_R^2 + \epsilon_{t}~;~~~ \epsilon_{t} \sim \Norm (0, \sigma_R^2) \, ,~ 1 \leq t \leq T \minus 1
  \eeq \\

\\[-3.5ex]
\begin{fleqn}
\begin{equation}
\elabel{rbias}
\text{~~~where~~} b_{t} = \left\{
 \begin{array}{ll}
 0  & ;~~t \leq t_1^b\\
 b_{\mr{max}} \left[ 1 - (t - t_1^b) / (t_2^b - t_1^b) \right]  & ;~~t_1^b < t < t_2^b\\
 b_{\mr{max}}  & ;~~t_2^b \leq t \leq t_3^b\\
 b_{\mr{max}} \left[ 1 - (t_3^b - t) / (t_4^b - t_3^b) \right]  & ;~~t_3^b < t < t_4^b\\
 0  & ;~~t_4^b \leq t
 \end{array}
\right.
\end{equation}
\end{fleqn}\\

% \, ; ~~ 1 \leq t \leq T-1~~~~~\text{**** needs proofing}
% Two equations for if there was error in initial age structure _s
% \beq \xi_{as} = \log N_{a1s} - \log R_0 + \log 2 + M(a - 1) + \sigma_I^2  \, ;~~1 \leq a \leq A-1, s = 1,2 \label{xias} \eeq \vsd

% \beq \xi_{As} = \log N_{A1s} - \log R_0 + \log 2 + M(A - 1) + \log (1 - e^{- M}) + \sigma_I^2  \, ; s = 1,2  \label{xiAs}  \eeq \vsd

\bec {\bf Log-likelihood components ($\isactive$~active, $\inactive$~inactive)} \eec

\beq \elabel{ll1}
  \isactive~ \Lagr_{1g}(\bfTh | \{ \widehat{I}_{tg} \} ) = \sum_{t \in {\bf T}_g} \left[ \frac{ ( \log I_{tg} - \log (q_g B_{tg}) )^2 }{2 \kappa_{tg}^2 } + \kappa_{tg}^\prime \log \kappa_{tg} \right]
  \eeq \\

\beq \elabel{ll2}
  \inactive~ \Lagr_{2g}(\bfTh | \{ d_{tg} \} ) = \sum_{t=1}^T  0.5 (\mr{df}_g + 1) \log \left[ \frac{ 1 + ( d_{tg} - \widehat{d}_{tg} )^2 }{ \mr{df}_g \delta_{tg}^2 }  \right] + \delta_{tg}^\prime \log \delta_{tg}
  \eeq \\

\beq \elabel{ll3}
  \inactive~ \Lagr_{3g}(\bfTh | \{ \widebar{w}_{tg} \} ) = \sum_{t=1}^T 0.5 (\mr{df}_{\widebar{w}} + 1) \log \left[ \frac{ 1 + ( \widebar{w}_{tg} - \widehat{\widebar{w}}_{tg} )^2 }{ \mr{df}_{\widebar{w}} \psi_{tg}^2 }  \right] + \psi_{tg}^\prime \log \psi_{tg}
  \eeq \\

\beq \elabel{ll4}
  \inactive~ \Lagr_{4g}(\bfTh | \{ l_{tg} \} ) = \sum\nolimits_{t \in {\bf U}_g} \sum\nolimits_{s=1}^2 \sum\nolimits_{l=1}^L n_{\ds tgs} \, p_{\ds ltgs} \, \log \, ( p_{\ds ltgs} / \, \widehat{p}_{\ds ltgs} ) \text{\footnotesize \,; composition option\,1\normalsize}
  \eeq \\

\beq \elabel{ll5}
  \isactive~ \Lagr_{5g}(\bfTh | \{ a_{tg} \} ) = \sum\nolimits_{t \in {\bf U}_g} \sum\nolimits_{s=1}^2 \sum\nolimits_{a=1}^A n_{\ds tgs} \, p_{\ds atgs} \, \log \, ( p_{\ds atgs} / \, \widehat{p}_{\ds atgs} ) \text{\footnotesize \,; composition option\,2\normalsize}
  \eeq \\

\beq \elabel{ll6}
  \inactive~ \Lagr_{6g}(\bfTh | \{ z_{tg} \} ) = \sum\nolimits_{t \in {\bf U}_g} \sum\nolimits_{s=1}^2 \sum\nolimits_{z=1}^{\Lambda} n_{\ds tgs} \, p_{\ds ztgs} \, \log \, ( p_{\ds ztgs} / \, \widehat{p}_{\ds ztgs} ) \text{\footnotesize \,; composition option\,3\normalsize}
  \eeq \\

\beq \elabel{ll7}
  \isactive~ \Lagr_{7g}(\bfTh | \{ C_{tg} \} ) = \sum\nolimits_{t=1}^{T}  \, \left[ \log C_{tg} - \log ( \widehat{C}_{tg} + 1\mr{e}\minus6 ) \right]^2 / ~ 2 \tau_{tg}^2
  \eeq \\

\beq \elabel{llR}
  \isactive~ \Lagr_{R}(\bfTh | \{ R_{t} \} ) = 0.5 \, \sum\nolimits_{t=1}^{T} \, ( \widetilde{R}_t^2 / \sigma_R^2 ) + b_t \log \sigma_R^2
  \eeq \\

\beq \elabel{llphi.norm}
  \isactive~ \Lagr_{\phi_j}(\bfTh | \{ \phi_j \} ) = 0.5 \, \left[ ( \phi_j - \mu_{\phi_j} ) / \sigma_{\phi_j}  \right]^2 \text{\footnotesize ~~~; normal prior distributions for parameter $j$\normalsize}
  \eeq \\

\beq \elabel{llphi.lnorm}
  \isactive~ \Lagr_{\phi_j}(\bfTh | \{ \phi_j \} ) = 0.5 \, \left[ ( \log \phi_j - \mu_{\phi_j} ) / \sigma_{\phi_j}  \right]^2 \text{\footnotesize ~~~; lognormal prior distributions for parameter $j$\normalsize}
  \eeq \\

\beq \elabel{llP}
  \inactive~ \Lagr_{P_j}(\bfTh | \{ P_{jt} \} ) = ( 1 / 2\sigma_P^2 ) \, \sum\nolimits_{t=1}^{T} \, \widetilde{P}_{jt}^2 \text{\footnotesize ~~~; for time-varing parameters, if any\normalsize}
  \eeq \\

\bec {\bf Objective function} \eec

\beq \elabel{Fobj}
  \Fobj(\bfTh) = \sum_{i=1}^{7} \sum_{g=1}^{G} \omega_{ig} \Lagr_{ig} + \omega_{R} \Lagr_{R} + \sum_{\phi} \omega_{\phi} \Lagr_{\phi} + \sum_{P} \omega_{P} \Lagr_{P}~~ ; \omega \text{\footnotesize \,= weighting factors for each~} \Lagr
  \eeq \\

\\[-0.5ex]\hline

\end{longtable}
\clearpage

%\comment{
%\textbf{Temporary Notes:}
%\begin{itemize_csas}
%\item \newstuff{Text in blue indicates new or revised material for scrutiny.}
%\item \greystuff{Text in grey indicates material that has yet to be determined.}
%\item \oldstuff{Text in red indicates material from a previous assessment that needs revision to reflect current assessment.}
%\end{itemize_csas}
%}

% ********************** Table 4 ************************************
\subsection{Base run prior expectation}

\begin{longtable}{L{1.3in}C{0.8in}C{1.0in}C{1.4in}C{0.9in}C{1.0in}}
\caption{Details for estimation of parameters, including prior distributions with corresponding means and standard deviations, bounds between which parameters are constrained, and initial values to start the minimisation procedure for the MPD (mode of the posterior density) calculations. In SS3, an analytical solution for $q$ is calculated when the parameter is allowed to `float'.}
%\comment{
%% For uniform prior distributions, the bounds completely parameterise the prior.
%% The resulting non-uniform prior probability density functions are the $\phi_j(\bfTh)$ functions that contribute to the joint prior distribution in \eref{jointprior}.
%}
\label{tab:priors}
\\ \hline\\[-2.2ex]
\textbf{Parameter} & \textbf{Phase} & \textbf{Prior distribution} & \textbf{Mean, SD} & \textbf{Bounds} & \textbf{Initial value}
\\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
\textbf{Parameter} & \textbf{Phase} & \textbf{Prior distribution} & \textbf{Mean, SD} & \textbf{Bounds} & \textbf{Initial value}
\\[0.2ex]\hline\\[-1.5ex] \endhead
\hline\\[-2.2ex]   \endfoot  \hline \endlastfoot  %

% copy table from Sweave tex file
\textbf{Multi-area model}      &    &           &                   &             &\\
$M_{1}$ (female)               &  4 & normal    & 0.06, 0.018       & [0.02, 0.2] &  0.06\\
$M_{2}$ (male)                 &  4 & normal    & 0.06, 0.018       & [0.02, 0.2] &  0.06\\
$h$                            &  5 & beta      & 0.67, 0.17        & [0.2, 1]    &  0.67\\
$\log R_0$                     &  1 & normal    & 10, 10            & [1, 16]     &  10\\
$\mathring{p}_{\alpha=1}$       &  3 & normal    & 0, 1              & [-5, 5]     &  0\\
$\mathring{p}_{\alpha=2}$       &  3 & normal    & 0, 1              & [-5, 5]     &  0\\
$\log q_{1,...,8}$             & -1 & analytic  & -3,   6           & [-15, 15]   & -3\\
$\mu_{1}$                      &  3 & normal    & 10, 10            & [5, 40]     & 10\\
$\mu_{2,3} \sim \mu_{1}$       &  - & linked    & ---               & ---         & ---\\
$\mu_{4,5}$                    &  3 & normal    & 12, 12            & [5, 40]     & 12\\
$\mu_{6}$                      &  3 & normal    & 12, 3.6           & [5, 40]     & 12\\
$\mu_{7,8}$                    &  3 & normal    & 12, 3.6           & [0, 40]     & 12\\
$\mu_{9} \sim \mu_{7}$         &  - & linked    & ---               & ---         & ---\\
$\log v_{\text{L}1}$           &  4 & normal    & 2, 2              & [-15, 15]   & 2\\
$\log v_{\text{L}2,3} \sim \log v_{\text{L}1}$ & 4 & linked        & ---  & ---  & ---\\
$\log v_{\text{L}4,5}$         &  4 & normal    & 2.5, 2.5          & [-15, 15]   & 2.5\\
$\log v_{\text{L}6,7,8}$       &  4 & normal    & 2.5, 0.75         & [-15, 15]   & 2.5\\
$\log v_{\text{L}9} \sim \log v_{\text{L}7}$   & 4 & linked        & ---  & ---  & ---\\
$\Delta_{1,...,8}$             &  4 & normal    & 0, 1              & [-8, 10]    & 0\\
$\Delta_{9} \sim \Delta_{7}$   &  4 & linked    & ---               & ---         & ---\\
\hline  
\end{longtable}

%\medskip

%%==========================================================
\section{DESCRIPTION OF DETERMINISTIC COMPONENTS}

Notation (Table~\ref{tab:notate}) and deterministic components (Table~\ref{tab:detcomp}) are described below. Acronyms: SS3~= Stock Synthesis~3, AW~= Awatea, AF~= age frequencies|proportions, \spc~= \spn.

%currentRes = importRes("C:/Users/haighr/Files/GFish/PSARC13/SGR/Data/Awatea/CST/SGRrun16/SGR-CST.16.03.res", Dev=TRUE, CPUE=TRUE, Survey=TRUE, CLc=TRUE, CLs=TRUE, CAs=TRUE, CAc=TRUE, extra=TRUE)

\subsection{Age classes}

Index (subscript) $a$ represents age classes, going from 1 to the accumulator age class $A$ of \Sexpr{texThatVec(Amax)}. 
Age class $a=5$, for example, represents fish aged 4-5 years (which is the usual, though not universal, convention, \citealt{Caswell:2001}), and so an age-class~1 fish was born the previous year.
Unlike Awatea, SS3 uses an age class 0 that presumably represents fish at birth (new recruits).
The variable $N_{ats}$ is the number of age-class $a$ fish of sex $s$ at the \textit{start} of year $t$, so the model is run to year $T$ which corresponds to the beginning of year \finalYr.

\subsection{Years}

Index $t$ represents model years, going from $1$ to $T=\Sexpr{Tmax}$, and $t=0$ represents unfished equilibrium conditions. 
The actual year corresponding to $t=1$ is \Sexpr{startYear}, and so model year $T=\Sexpr{Tmax}$ corresponds to \finalYr.
The interpretation of year depends on the model's derived state or data input:
\begin{itemize_csas}{}{}
\item beginning of year: $N_{ats}$, $B_t$, $R_t$
\item middle of year: $C_{tg}$, $V_{tg}$, $F_{tg}$, $u_{tg}$, $\widehat{I}_{tg}$, $\widehat{p}_{atgs}$
\end{itemize_csas}

\subsection{Commercial Data}

As described in \AppCat, the commercial catch was reconstructed back to 1918 for five fisheries -- (1)~trawl, (2)~halibut longline, (3)~sablefish trap|longline, (4)~dogfish|lingcod|salmon troll, and (5)~hook \& line rockfish in outside (offshore) waters -- all excluding PMFC area 4B (Strait of Georgia).
In this assessment, three commercial fleets were used -- `Trawl\,+\,Other' in three regions or areas (5ABC, 3CD, 5DE), where `Other' refers to negligible non-trawl fisheries.
Given the small catches in the early years, the model was started in \Sexpr{startYear}, with catches prior to \Sexpr{startYear} not considered.
The time series for catches by fleet are denoted $C_{tg}$ and include retained and discarded catches (either observed or reconstructed). 
The set ${\bf U}_{1,2,3}$ (Table~\ref{tab:notate}) gives the years of available ageing data from the commercial fishing fleets.
The proportions-at-age values are given by $p_{atgs}$ with observed sample size $n_{tg}$, where $g=1,2,3$ corresponds to the commercial fleets.
The proportions are calculated using the stratified weighting scheme, described in \AppBio, that adjusts for unequal sampling effort across temporal and spatial strata.

\subsection{Survey Data} 
<<surveydata, echo=FALSE, eval=TRUE, results=hide>>= ## hide the results
insert.surveys = 
if (Nstock==1) {
	paste0(unlist(sapply(1:Nstock,function(i){paste0(" $g$=",gS[[i]],": ",texShit[["gnam"]][[i]][gS[[i]]])})),collapse="; ")
} else {
	paste0(unlist(sapply(1:Nstock,function(i){paste0(stock.name[i]," $g$=",gS[[i]],": ",texShit[["gnam"]][[i]][gS[[i]]])})),collapse="; ")
}
@
Survey data from six fleets ($g{=}\gsurv$) were used in the model, as described in detail in \AppSurv.
These surveys are indexed using $g$, with each subscript corresponding to a survey: \Sexpr{insert.surveys}.
The years for which data were available for each survey are given in Table~\ref{tab:notate};
${\bf T}_g$ corresponds to years for the survey biomass estimates $I_{tg}$ (and corresponding standard deviations $\kappa_{tg}$), and ${\bf U}_g$ corresponds to years for proportion-at-age data $p_{atgs}$ (with observed sample sizes $n_{tg}$).
Note that for surveys, sample size refers to the number of tows sampled, where each sample comprises specimens, typically $\sim$10-50 fish/sample.

\subsection{Sex}

A two-sex model was used, with subscript $s{=}1$ for females and $s{=}2$ for males (note that these subscripts are the reverse of the codes used in the GFBioSQL database). 
Ageing data were partitioned by sex, as were the weights-at-age inputs. 
Selectivities and natural mortality were specified by sex.

\subsection{Weights-at-age}

The weights-at-age $w_{as}$ were assumed fixed over time and were based on sex-specific allometric (length-weight) and growth (age-length) model parameters derived from the biological data; see \AppBio{} for details.

\subsection{Maturity of females}

The proportion of age-class $a$ females that are mature is $m_a$, and was assumed to be invariant over time; see \AppBio{} for details.
Fecundity-at-age for females was assumed to be proportional to their weights-at-age.

\subsection{Initial conditions}

An unfished equilibrium at the beginning of the reconstruction was assumed because there was no evidence of significant removals prior to \Sexpr{startYear}.
The initial conditions \eref{Na0s} and \eref{NA0s} were obtained by setting $R_t = R_0$ (virgin recruitment), $N_{ats} = N_{a1s}$ (equilibrium condition) and $u_{ats} = 0$ (no fishing).
The virgin spawning biomass $B_0$ was obtained from \eref{B0}.
The initial lengths were set using the growth equations of \citet{Schnute:1981} \eref{La0s}-\eref{LA0s}.

\subsection{State dynamics}

The core of the model is the set of dynamic equations \eref{Nats} for the estimated number $N_{ats}$ of age-class $a$ fish of sex $s$ at the start of year $t$. 
The proportion of female new recruits $c$ in Equation \eref{Nats} was set to 0.5.
Equation \eref{Nats} calculates the numbers of fish in each age class (and of each sex) that survive to the following year, where $Z_{ats}$ represents the total mortality rate, which in this case comprises the sum of natural mortality $M$ and fishing mortality $F$. 
The accumulator age class $A$ retains survivors from this class in following years.

Natural mortality $M_s$ was estimated separately for males and females.
This parameter enters the equations in the form $e^{-M_s}$ as the proportion of unfished individuals that survive the year.

\subsection{Selectivities} \label{ss:select}

Separate selectivities were estimated for each of the fleets with AF data using SS3's selectivity pattern~20 for females (Equations~\ref{Satgs}-\ref{gammas}) and selectivity option~3 for males.
%%rm (although \Sexpr{spp.code} male selectivity was fixed to be the same as that for females in this assessment).
Note that `log' herein refers to natural logarithms. %%; `AW' denotes Awatea and `SS3's denotes Stock Synthesis 3.
Pattern 20 describes double normal selectivity for females where the parameters $\beta_i$ ($i=1,...,6$) for fleet $g$ are:
%%\vspace{-0.5\baselineskip}%  because topsep doesn't work

\begin{enumerate_itemize}{}{}
  \item $\beta_{1g}$ -- age at which selectivity first reaches maximum selectivity:
    \begin{enumerate_itemize}{-0.25}{-0.25}
      \item SS3: beginning age (year) for the plateau;
      \item AW: age of full selectivity ($\mu_g$) for females;
    \end{enumerate_itemize}
  \item $\beta_{2g}$ -- (SS3 only) used to generate a logistic between peak ($\beta_{1g}$) and maximum age ($A$) that determines width of top plateau ($a_g^{\star} - \beta_{1g}$), where $a_g^{\star}$ is the final age of the top plateau;
%  \begin{enumerate_itemize}{}{}
%    \item where width $w_\text{T} = \beta{1g} + \pi_{\text{T}g} + (0.99A - \pi_{\text{T}g}) / (1+e^{-\pi_{\text{T}g}})$;
%  \end{enumerate_itemize}
  \item $\beta_{3g}$ -- used to determine width of the ascending limb of double normal curve:
    \begin{enumerate_itemize}{-0.25}{-0.25}
      \item SS3: determines slope of ascending limb by tweaking its variance;
      \item AW: log of variance for left limb ($v_{\mr{L}g}$) of selectivity curve;
    \end{enumerate_itemize}
  \item $\beta_{4g}$ -- used to determine width of the descending limb of double normal curve:
    \begin{enumerate_itemize}{-0.25}{-0.25}
      \item SS3: determines slope of descending limb by tweaking its variance;
      \item AW: log of variance for right limb ($v_{\mr{R}g}$) of selectivity curve;
    \end{enumerate_itemize}
  \item $\beta_{5g}$ -- (SS3 only) determines initial selectivity by generating a logistic between 0 and 1 at first age;
    \begin{enumerate_itemize}{-0.25}{-0.25}
      \item where selectivity $S_{a{=}1,g} = 1/(1+e^{-\beta_{5g}})$; however,
      \item use -999 to ignore initial selectivity algorithm and decay small-fish selectivity using $\beta_{3g}$;
    \end{enumerate_itemize}
  \item $\beta_{6g}$ -- (SS3 ony) determines final selectivity by generating a logistic between 0 and 1 at final age bin;
    \begin{enumerate_itemize}{-0.25}{-0.25}
      \item where selectivity $S_{Ag} = 1/(1+e^{-\beta_{6g}})$.
    \end{enumerate_itemize}
\end{enumerate_itemize}

Option 3 for pattern 20 describes male selectivity as offsets to female selectivity, where parameters $\Delta_i$ ($i=1,...,5$) for fleet $g$ are:
\begin{enumerate_csas}{}{}
\item $\Delta_{1g}$ = male peak offset ($\Delta_g$ in AW) added to the first female selectivity parameter, $\beta_{1g}$ ($\mu_g$ in AW);
\item $\Delta_{2g}$ = male width offset (log width) added to the third selectivity parameter, $\beta_{3g}$ (same as female $v_{\text{L}g}$ in AW);
\item $\Delta_{3g}$ = male width offset (log width) added to the fourth selectivity parameter, $\beta_{4g}$ (same as female $v_{\text{R}g}$ in AW);
\item $\Delta_{4g}$ = male plateau offset added to the sixth selectivity parameter, $\beta_{6g}$ (not present in AW);
\item $\Delta_{5g}$ = apical selectivity for males (usually 1 but could be different than that for females; not present in AW).
\end{enumerate_csas}

Dome selectivity only occurs under three conditions:\\
\begin{itemize_csas}{-0.25}{}
  \item the width of the top plateau (between $\beta_{1g}$ and $a_g^{\star}$) must be less than $A - \beta_{1g}$;
  \item the steepnees of the descending limb (controlled by $\beta_{4g}$) must not be too shallow; and 
  \item the final selectivity (controlled by $\beta_{6g}$) must be less than peak selectivity (usually 1).
\end{itemize_csas}
Generally for males, the same selectivity function is used except that some of the selectivity parameters ($\beta_{ig}$ for $i\in \{1,3,4,6\}$) may be shifted if male AF data are sufficiently different from female AF data.

\subsection{Derived states}

The spawning biomass (biomass of mature females, in tonnes) $B_t$ at the start of year $t$ is calculated in \eref{Bt} by multiplying the numbers of females $N_{at1}$ by fecundity $f_a$ \eref{fa}, which is a function of a length-age matrix $\varphi_{lats}$ \eref{len.age}, the maturity ogive ($m_l$), egg production ($o_l$), and weights-at-length $w_{l1}$ \eref{wls}.

The fishing mortality rate $F_{tg}$ \eref{Ftg} is derived through an iterative process to fit observed catches closely rather than removing the catches by subtraction.
A mid-season harvest rate is calculated using Pope's approximation \citep{Pope:1972}, which is then converted to an instantaneous $F$ using the Baranov equation \citep{Baranov:1918}.
Each fleet's approximate $F$ is repeated iteratively several times (usually three to four) using the Newton-Rhapson procedure until its value yields a close match to the observed catches by the fleet.
Details can be found in \citet{Methot-Wetzel:2013}.

Although SS3 does not report vulnerable biomass \textit{per~se}, equation \eref{Vtg} provides an equation from Awatea for $V_{tg}$ mid-year.
Assuming that $C_{tg}$ is taken mid-year, the harvest rate is simply $C_{tg} / V_{tg}$.
Further, for year $t$, the proportion $u_{tg}$ of age-class $a$ and sex $s$ fish that are caught in fishery $g$ can be calculated by multiplying the commercial selectivities $S_{atgs}$ and the ratio $u_t$ \eref{Vtg}.

\subsection{Stock-recruitment function} \label{ss:stock-recruit}

A Beverton-Holt recruitment function is used, parameterised in terms of steepness, $h$, which is the proportion of the long-term unfished recruitment obtained when the stock abundance is reduced to 20\pc{} of the virgin level \citep{Mace-Doonan:1988, Michielsens-McAllister:2004}.
Awatea uses a prior on $h$ taken from \citet{Forrest-etal:2010}, where shape parameters for a beta distribution are $\alpha = (1 - h) B_0 / (4 h R_0)$ and $\beta = (5 h - 1) / 4 h R_0$ (\citealt{Hilborn-etal:2003, Michielsens-McAllister:2004}). 
Substituting these into the Beverton-Holt equation, $R_t = B_{t-1} / (\alpha + \beta B_{t-1})$, where $R_0$ is the virgin recruitment, $R_t$ is the recruitment in year $t$, $B_t$ is the spawning biomass at the start of year $t$, and $B_0$ is the virgin spawning biomass.
SS3 offers several recruitment options including Ricker, Beverton-Holt, and a three-parameter survivorship-based function suitable for low-fecundity species \citep{Taylor-etal:2013}.

The multi-area model in SS3 estimates one recruitment for the coastwide population, which is then allocated amongst the three areas: 5ABC, 3CD, and 5DE. 
Two allocation parameters (number areas - 1) are estimated in natural log space, while the third parameter is fixed at zero. 
The equation to calculate the proportion allocations by area $\alpha$ in linear space is:
\eb
p^{R}_{\alpha} = e^{\mathring{p}_{\alpha}} / ( e^{\mathring{p}_{\alpha=1}} + e^{\mathring{p}_{\alpha=2}} + e^{\mathring{p}_{\alpha=3}} ) \text{,~~where~} \alpha \in{1,2,3}
\label{pR.normal}
\ee \\[-0.25ex]
In order to have varying recruitment by year in each area, a time-varying component was added to $p^{R}_{\alpha}$ by estimating annual deviance parameters $\nu_{t,\alpha}$.
The period over which this was applied varied among areas and runs: 1935 to 2014 for 5ABC (Base and Sensitivity S03), 1975 to 2014 for 3CD (Base and S02), and 1935 to 2014 for 5DE (S02 and S03).
These years were selected based on the availability of age frequency data and the number of observations obtained for a cohort.
Additionally, a standard error ($\zeta_{\alpha}$) for the deviance values can be estimated; however, this stock assessment fixed $\zeta_{\alpha}$ to 1. 
Annual time-varying recruitment proportions are then calculated by adjusting the estimated proportions in log space:
\eb
\mathring{p}_{t,\alpha} = \mathring{p}_{\alpha} + \nu_{t,\alpha} \zeta_{\alpha}
\label{pR.tv}
\ee \\[-0.25ex]
and then applying \eref{pR.normal} to transform these annually adjusted values into linear space, $p^{R}_{t,\alpha}$.

\subsection{Fitting to data}

Model estimates of the survey biomass indices $I_{tg}$ are denoted $\widehat{I}_{tg}$ and are calculated in \eref{Itg.hat}.
The estimated numbers $N_{ats}$ are multiplied by the natural mortality term $e^{-M_s / 2}$ (that accounts for half of the annual natural mortality), the term $1 - u_{ats} / 2$ (that accounts for half of the commercial catch),  weights-at-age $w_{as}$ (to convert to biomass), and selectivity $S_{ags}$. 
The sum (over ages and sexes) is then multiplied by the catchability parameter $q_g$ to give the model biomass estimate $\widehat{I}_{tg}$. 

The estimated proportions-at-age $\widehat{p}_{atgs}$ are calculated in \eref{patgs.hat}. 
For a particular year and gear type, the product $e^{-M_{s}/2} (1 - u_{ats}/2) S_{ags} N_{ats}$ gives the relative expected numbers of fish caught for each combination of age and sex. 
Division by $\sum_{s=1}^2 \sum_{a=1}^A e^{-M_{s}/2} (1 - u_{ats}/2) S_{ags} N_{ats}$ converts these to estimated proportions for each age-sex combination, such that $\sum_{s=1}^2 \sum_{a=1}^{A} \widehat{p}_{atgs} = 1$.

Ageing error (AE) in this stock assessment was applied using SS3's vector-style inputs of bias and precision.
The bias vector used was 0.5 to 60.5 at increments of 1 year for ages 0 through 60, which in SS3 signifies no age bias.
The precision vector for ages 0 through 60 was estimated as the standard deviation of ages 1 through 61 calculated from the CVs of lengths-at-age:
~~~$\sigma_a = a (\sigma_{L_a} / \mu_{L_a})$, where $a=1,...,61$.
Using these vectors, SS3 applies a cumulative normal distribution for each age to calculate the frequency of expected age given a mean assigned age and standard deviation (see~\ref{age.err}).

\begin{chapquote}{Richard Methot, 2021, \textit{pers. comm.}}
``SS3 never adjusts input data.  Rather, it adjusts expected values for data to take into account known factors that influenced the creation of the observations. So, ageing error is applied to a modeled distribution of true ages (after selectivity has taken a subset from the population) to create a new distribution of ages that includes the influence of ageing error.''
\end{chapquote}

%%==========================================================
\section{DESCRIPTION OF STOCHASTIC COMPONENTS}

\subsection{Parameters}

The set $\bfTh$ gives the parameters that are estimated. 
The estimation procedure is described in the Bayesian Computations section below.

\subsection{Recruitment deviations}

For recruitment, a log-normal process error is assumed, such that the stochastic version of the deterministic stock-recruitment function (\ref{Rt}) is
\eb
R_t = \frac{B_{t-1}}{\alpha + \beta B_{t-1}} e^{\minus 0.5 b_t \sigma_R^2 + \epsilon_t} \label{Rt.sto}
\ee \\[-0.25ex]

%%e^{\minus 0.5 b_t \sigma_R^2 + \epsilon_t}~;~~~ \epsilon_t \sim \Norm (0, \sigma_R^2)

where $\epsilon_t \sim \Norm(0, \sigma_R^2)$, and the bias-correction term $-b_t \sigma_R^2/2$ term in \eref{Rt.sto} ensures that the mean of the recruitment deviations equals 0. 
This then gives the recruitment deviation equation (\ref{rdevs}) and log-likelihood function (\ref{llR}). 
In this assessment, the value of $\sigma_R$ was fixed at \Sexpr{sigmaR} based on values used in recent BC rockfish stock assessments.
Other assessments have used $\sigma_R$ = 0.6 following an assessment of Silvergray Rockfish \citep{Starr-etal:2016_sgr} in which the authors stated that the value was typical for marine `redfish' \citep{Mertz-Myers:1996}.
An Awatea model of Rock Sole used $\sigma_R$~= 0.6 \citep{Holt-etal:2016_rol}, citing that it was a commonly used default for finfish assessments \citep{Beddington-Cooke:1983}.
In recent BC rockfish assessments, we have adopted $\sigma_R$~= 0.9 based on an empirical model fit consistent with the age composition data for 5ABC POP \citep{Edwards-etal:2012_pop5ABC}.
A study by \citet{Thorson-etal:2014} examined 154 fish populations and estimated $\sigma_R$~= 0.74 (SD=0.35) across seven taxonomic orders; the marginal value for Scorpaeniformes was $\sigma_R$=0.78 (SD=0.32) but was only based on 7 stocks.

Most BC offshore rockfish models in past (using Awatea 2009--2020 and SS3 2021-2022) have used a recruitment deviation vector (during the main recruitment period) that sums to 0; however, a \href{https://github.com/admb-project/admb/issues/107}{bug in ADMB} became apparent to Ian Taylor when running MCMC simulations. Using the command line option \code{-mcmc}, the value of \code{sum(effort\_devs)} was never close to 0, but using the option \code{-mceval} (i.e., evaluate the contents of \code{[model].psv}), \code{sum(effort\_devs)} was very close to 0.
One of the consequences was that $\sim$10\pc{} of the posterior samples lead to a \href{https://groups.google.com/a/admb-project.org/g/developers/c/8QNAd3a_iGQ}{crashed population}.
During the current POP model runs, evaluated MCMC posterior samples led to 35 out of 2000 samples (1.75\pc{}) with undefined MSY values (specified as \code{`NaN'}, or not a number).
The population had not crashed but the forecast fishing mortality had been evaluated as \code{`NaN'} for no apparent reason.

\subsection{Log-likelihood functions}

The objective funtion function $\Fobj(\bfTh)$ \eref{Fobj} comprises a weighted sum of individual likelihood components that include:
\begin{itemize_csas}{}{}
  \item $\Lagr_{I_g}$ \eref{ll1} -- CPUE or abundance index by fleet
  %%\item $\Lagr_{d_g}$ \eref{ll2} -- discarded biomass by fleet
  %%\item $\Lagr_{\widehat{w}_g}$ \eref{ll3} -- mean body weight by fleet
  %%\item $\Lagr_{l_g}$ \eref{ll4} -- length composition by fleet
  \item $\Lagr_{a_g}$ \eref{ll5} -- age composition by fleet
  %%\item $\Lagr_{z_g}$ \eref{ll6} -- mean size-at-age by fleet
  \item $\Lagr_{C_g}$ \eref{ll7} -- catch by fleet
  \item $\Lagr_{R}$ \eref{llR}   --  recruitment deviations
  \item $\Lagr_{\phi_j}$ \eref{llphi.norm} to \eref{llphi.lnorm} -- parameter priors
  \item $\Lagr_{P_j}$ \eref{llP} -- random parameter deviations
\end{itemize_csas}
See \citet{Methot-Wetzel:2013} and \citet{Methot-etal:2021} for more likelihood options and details.

%%==========================================================
\section{BAYESIAN COMPUTATIONS}

Estimation of parameters compares the estimated (model-based) observations of survey biomass indices and proportions-at-age with the data, and minimises the recruitment deviations. 
This is done by minimising the objective function $f(\bfTh)$, which equation \eref{Fobj} shows is the negative of the sum of the total log-likelihood function comprising the logarithmic components \eref{ll1}-\eref{llP}.

%%\newpage
The procedure for the Bayesian computations is as follows:
\begin{enumerate_csas}{}{}
  \item minimise the objective function $f(\bfTh)$ to give estimates of the mode of the posterior density (MPD) for each parameter: (a)~done in phases, and (b)~ perform a reweighting;
  \item generate samples from the joint posterior distributions of the parameters using Monte Carlo Markov Chain (MCMC) procedure, starting the chains from the MPD estimates.
\end{enumerate_csas}

\subsection{Phases}

The MPD estimates were obtained by minimising the objective function $f(\bfTh)$, from the stochastic (non-Bayesian version) of the model. 
The resulting estimates were then used to initiate the chains for the MCMC procedure for the full Bayesian model.

Simultaneously estimating all the estimable parameters for complex nonlinear models is ill advised, and so ADMB allows some of the estimable parameters to be kept fixed during the initial part of the optimisation process \citet{ADMB:2009}. 
Some parameters are estimated in phase~1, then some further ones in phase~2, and so on. 
The order (if estimated) typically used by the BC Offshore Rockfish assessment team is:

\begin{changemargin}{0.25in}{0.25in}{0.5ex}
phase 1: virgin recruitment $R_0$ and survey catchabilities $q_{\gsurv}$\\
  \hsd (although the $q$ fit herein adopts a `float' option, which calculates an analytical solution);\\
phase 2: recruitment deviations $\epsilon_t$ (held at 0 in phase 1);\\
phase 3: natural mortality $M_{s}$ and age of full selectivity for females $\beta_{1g}$ for $g{=}\ugees$;\\
phase 4: additional selectivity parameters $\beta_{ng}$ for $n{=}2,...,6$ and $g{=}\ugees$;\\
phase 5: steepness $h$.
\end{changemargin}

\subsection{Reweighting} \label{ss:reweight}

\begin{chapquote}{Allan Hicks, IPHC, Aug 17, 2021, \textit{pers. comm.}}
``Sample sizes are used to calculate the variance for a data source and are useful to indicate the relative differences in uncertainty across years within each data source.
However, sample size may not represent the relative difference in the variance between different data sources (usually abundance vs. composition).
Therefore, the relative weights for each data source in an integrated stock assessment should be adjusted to reflect the information content of each, while retaining the relative differences across years.
This can be accomplished by applying adjustment factors to abundance and composition data to weight either data source up or down relative to the other.
''
\end{chapquote}
Previous rockfish stock assessments using the Awatea platform (from 2011) adopted the \citet{Francis:2011} reweighting approach -- adding series-specific process error to abundance index CVs on the first reweight, and iteratively reweighting age frequency (composition data) sample size by mean age on the first and subsequent reweights.

\subsubsection{Abundance} \label{sss:rwt_abund}

<<tex.the.cvpro, echo=FALSE, eval=TRUE, results=hide>>= # hide the results 
##----------------------------
##cvpro=c(cvpro,cvpro); names(cvpro)=c("here","there"); Nstock=2 ## just for testing
rubbish  = sapply(cvpro,function(x){texThatVec(x,simplify=F)})
Nseries  = sapply(cvpro,length)
texcvpro = paste0( rubbish," ", ifelse(Nstock*Narea==1,"along ","in "), if(Nstock*Narea>1) names(rubbish) else "the BC coast", " ($g$=", qgees, ")" )
@

For abundance data (survey indices, commercial CPUE indices), \citet{Francis:2011} recommends reweighting observed coefficients of variation, $c_0$, by first adding process error $c_\text{p} \sim$ 0.2 to give a reweighted coefficient of variation

\eb
c_1 = \sqrt{c_0^2 + c_\text{p}^2}~. \label{reweight}
\ee

Survey abundance indices for \spc{} exhibited moderate relative error, and so no additional error $c_\text{p}$ was added to these indices.

This stock assessment did not use commercial CPUE because \Sexpr{spp.code} is targeted by the trawl fleet, and because the survey indices provided sufficient signals on abundance.
%%For information on a spline-smoother technique to calculate process error $c_\text{p}$, see \citet{Starr-Haigh:2022_ymr}.

For stock assessments using commercial CPUE, a procedure was developed for estimating process error $c_\text{p}$ to add to CPUE indices based on a spline-smoother analysis \citep{Starr-Haigh:2021_wwr}.
The idea for this analysis came from \citet{Francis:2011}, citing \citet{Clark-Hare:2006}, who recommended using a smoothing function to determine the appropriate level of process error to add to CPUE data, with the goal of finding a balance between rigorously fitting the indices while not removing the majority of the signal in the data.
\comment{
An arbitrary sequence of length 50, comprising degrees of freedom (DF,~$\nu_i$), where $i=2,...,N$ and $N$~= number of CPUE values $U_t$ from $t=\Sexpr{cpueLim[1]},...,\Sexpr{cpueLim[2]}$, was used to fit the CPUE data with a spline smoother.
At $i=N$, the spline curve fit the data perfectly and the residual sum of squares (RSS, $\rho_N$) was 0.
Using spline fits across a range of trial DF $\nu_i$, values of RSS $\rho_i$ formed a logistic-type curve with an inflection point at $i=k$ (Figure~\ref{fig:CPUEres-CVpro-CAR}).
The difference between point estimates of $\rho_i$ (proxy for the slope $\delta_i$) yielded a concave curve with a minimum $\delta_i$, which occurred close to the inflection point $k$.
At the inflection point $k$, $\nu_k$=~5.4 for \Sexpr{stock.lab[1]}, corresponding to $\rho_k$=~0.83, which was converted to $c_\text{p}$=~\Sexpr{cvpro[[1]][1]} using:
\vspace{-0.25\baselineskip}%% reduce space above
}
The equation for process error $c_\text{p}$ used in BC offshore rockfish stock assessments is:
\eb
c_\text{p} = \sqrt{\dfrac{\rho_k}{N-2}}~~~{\left[ \dfrac{1}{N} \sum\limits_{t=\Sexpr{cpueLim[1]}}^{\Sexpr{cpueLim[2]}} I_t \right]}^{-1}~, \label{cvpro.cpue}
\ee

where $\rho_k$~= residual sum of squares at inflection point $k$ after fitting a spline smoother with a range of degrees of freedom $v_i$~= 2 to $N$, $N$~= number of CPUE values from $t$=1996 to \prevYear, and $I_t$~= CPUE index at time $t$.

%For each model run, the abundance index CVs were adjusted on the first reweight only using the process error $c_\text{p}$~= \Sexpr{texcvpro}.

%% #1=figure1 #2=figure2 #3=label #4=caption #5=width (fig) #6=height (fig)
%%\onefigWH{CPUEres-CVpro-CAR}{Estimating process error to add to commercial CPUE data: top left -- residual sum of squares (RSS) from spline-smoother at various degrees of freedom; top right -- slope of RSS ($\sim$ first derivative), vertical dotted line at DF where slope is at a minimum; bottom left -- CPUE index data with spline-fitted DF=15.1 (dashed blue curve) and optimised DF=5.4 (solid red curve); bottom right -- standardised residual fit.}{4.5}{4.5}

\subsubsection{Composition} \label{sss:rwt_abund}

In a previous stock assessment \citep{Starr-Haigh:2023_car}, composition data were reweighted using the Dirichlet-Multinomial distribution available in SS3 \citep{Thorson-etal:2017}. 
This approach adds an estimable parameter ($\theta$) which automatically scales the input sample size as part of the likelihood.

\begin{chapquote}{Methot et al. (2021), \textit{Data Weighting}}
``In consultation with Jim Thorson, Ian Taylor proposed a normal $\Norm$(0,1.813) prior for
the \texttt{ln(DM\_parm)} parameters to counteract the effect of the logistic 
transformation between this parameter and the data weighting. The 1.813 value was
calculated as the standard deviation of the distribution of $\log(\theta)$ values derived from
starting with a uniform distribution on the weights, weight = $\theta/(1 + \theta) \sim \mathcal{U}(0,1)$,
and solving for $\log(\theta)$.''

\end{chapquote}

If the calculated weight $\theta/(1 + \theta)$ ratio is close to 1.0, the model is trying to tune the sample size as high as possible.
In this case, \citet{Methot-etal:2021} suggest fixing the $\log\,\text{DM}\,\theta$ parameter to a high value, like the upper bound of 20, which will result in 100\pc{} weight being applied to the input sample sizes.
One caveat of using the $\log\,\text{DM}\,\theta$ parameter is that it does not allow weights above 100\pc{} (by design).

\subsubsection{Selection of the Francis procedure for the base run} \label{sss:rwt_select}

The SS3 platform provides three options for weighting compositional data: the \citet{Francis:2011} mean-age procedure, the \citet{McAllister-Ianelli:1997} harmonic-mean procedure, and the self-weighting Dirichlet-Multinomial (D-M) option \citep{Thorson-etal:2017}, which estimates a weighting parameter for each compositional dataset.
Two of these procedures have been used in recent BC stock assessments: the D-M parameterisation for Canary Rockfish \citep{Starr-Haigh:2023_car} and the \citet{McAllister-Ianelli:1997} harmonic-mean procedure for Yellowmouth Rockfish \citep{Starr-Haigh:2022_ymr}.
Due to its ease of use, the D-M parameterisation was favoured initially for the 2023 POP multi-area stock assessment; however, the MCMC posterior for the $\mathring{p}_{\alpha=2}$ (\code{Rdist\_area(2)}, 3CD) parameter (see Table~\ref{tab:notate} and Section~\ref{ss:stock-recruit}) showed occasional excursions into implausibly high values, given the underlying data for the associated area.
Despite this, the bulk of the $\mathring{p}_{\alpha=2}$ posterior distribution was in a credible region, which allowed provisional acceptance of this model. 
On the other hand, the MCMC posterior for the same parameter in a model weighted using the \citet{Francis:2011} procedure, but otherwise using the same data and parameterisation as the D-M model (and using the Multinomial to fit AFs), was stable and showed no equivalent excursions to excessively large values.

Examination of the MCMC posterior estimates for the D-M $\theta$ parameter (Section~\ref{sss:rwt_abund}) showed that, while none approached the nominal upper bound of 10, the bulk of the distribution was between 5 and 6 (in natural log space), resulting in the model giving nearly full weight to the age frequency data.
It was suggested that this behaviour was due to the practice of using the number of sampled tows as the initial value for the compositional sample weight, resulting in relatively low sample weights for the AF data.
Unlike the \citet{Francis:2011} procedure, the D-M procedure cannot upweight compositional data. 
Consequently, if the AF data are highly informative, the D-M procedure will estimate large values for $\theta$, thus giving full weight to the compositional data (Section~\ref{sss:rwt_abund}). 
In order to test the proposition that the initial sample weights were affecting the $\theta$ parameter estimates, sample sizes using the number of age structures (otoliths) were tested. 
Both models were repeated, one using the D-M procedure and the other using the \cite{Francis:2011} procedure (Table~\ref{tab:rwt_multi}).

Column 3 (Francis) and column 5 (Dirichlet) in Table~\ref{tab:rwt_multi} demonstrate that the switch to the larger sample sizes determined from the number of otoliths was effective, with a strong drop in the Francis weights compared to the original values and a considerable drop in the estimated $\theta$ parameters for each AF data set. 
However, there was a loss of fit to the WCHG synoptic survey (likelihood rose from -4.4 to +6.2) by the second D-M model (although the likelihoods for the other two synoptic surveys did not change) while the two Francis models had similar fits to all three synoptic surveys.

More problematic was the shift in the distribution of biomass among the three areas estimated by the two D-M models. 
Table~\ref{tab:rwt_stock} shows that the total $B_0$ estimate for the sum of the three stocks dropped by nearly 40\pc{} between the two D-M runs, with similar proportional drops for $B_0$ in each area.
$B_{2024}$ also dropped between the two D-M runs, but by different levels in each of the three areas, leading to widely differing estimates of status relative to $B_0$.
These stock depletion estimates differed greatly from the D-M model estimates based on the low sample weights and from either of the \citet{Francis:2011} reweight estimates. 
On the other hand, the \citet{Francis:2011} reweight method appeared to be stable, returning similar estimates of $B_0$, $B_{2024}$, and $B_{2024}/B_0$ for all three areas under either of the two weighting options (Table~\ref{tab:rwt_stock}). 
This result gave confidence in the results generated by the \citet{Francis:2011} procedure and caused a switch to the \citet{Francis:2011} model as the base run, with the D-M model being relegated to a sensitivity run S01 (R17v18).

\begin{longtable}{L{1.25in}R{1in}R{1in}R{1in}R{1in}}
\caption{\citet{Francis:2011} reweight multiplier values for each AF data set for tow-based and otolith-based sample weights. Dirichlet-Multinomial MPD theta ($\theta$) parameter estimates for the same AF data sets and using the tow-based and otolith-based sample weights are shown in the final two columns.}
\label{tab:rwt_multi}
\\ \hline\\[-2.2ex]
 & \multicolumn{2}{c}{\textbf{Francis multiplier}} & \multicolumn{2}{c}{\textbf{D-M $\theta$ estimates}} \\
\textbf{SS3 fleet} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths}
\\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
 & \multicolumn{2}{c}{\textbf{Francis multiplier}} & \multicolumn{2}{c}{\textbf{D-M $\theta$ estimates}} \\
\textbf{SS3 fleet} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths}
\\[0.2ex]\hline\\[-1.5ex] \endhead
\hline\\[-2.2ex]   \endfoot  \hline \endlastfoot  %
%% manual copy from PJS docx
Trawl 5ABC     & 2.7923 & 0.0486 & 6.945 & -0.9737\\
Trawl 3CD      & 3.1274 & 0.0479 & 6.638 & -0.0746\\
Trawl 5DE      & 2.8821 & 0.0462 & 6.792 & -0.6878\\
QCS synoptic   & 0.5744 & 0.0197 & 5.877 & -0.6305\\
WCVI synoptic  & 1.0766 & 0.0521 & 5.727 & -0.4936\\
WCHG synoptic  & 1.2071 & 0.0951 & 6.018 &  0.7567\\
GIG historical & 0.7348 & 0.0330 & 4.642 & -1.1028\\
NMFS triennial & 0.4874 & 0.0173 & 5.447 & -0.3869\\
\hline  
\end{longtable}

\begin{longtable}{L{1.25in}R{1in}R{1in}R{1in}R{1in}}
\caption{MPD estimates of stock size at equilibrium and at the beginning of 2024, and stock depletion for the same runs as reported in Table~\ref{tab:rwt_multi}.  Note that biomass estimates have been rounded to nearest 100~t.}
\label{tab:rwt_stock}
\\ \hline\\[-2.2ex]
 & \multicolumn{2}{c}{\textbf{Francis multiplier}} & \multicolumn{2}{c}{\textbf{D-M $\theta$ estimates}} \\
\textbf{Area} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths}
\\[0.2ex]\hline\\[-1.5ex] \endfirsthead \hline 
 & \multicolumn{2}{c}{\textbf{Francis multiplier}} & \multicolumn{2}{c}{\textbf{D-M $\theta$ estimates}} \\
\textbf{Area} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths} & \textnormal{samples as \#~tows} & \textnormal{samples as \#~otoliths}
\\[0.2ex]\hline\\[-1.5ex] \endhead
\hline\\[-2.2ex]   \endfoot  \hline \endlastfoot  %
%% manual copy from PJS docx
\multicolumn{5}{l}{$B_0$ -- female spawning biomass at unfished equilibrium}\\
5ABC      & 56,000 & 54,500 &  66,400 & 41,300\\
3CD       & 18,700 & 18,100 &  22,600 & 13,400\\
5DE       & 18,900 & 18,300 &  21,400 & 13,300\\
Coastwide & 93,600 & 90,900 & 110,400 & 68,000\\
\multicolumn{5}{l}{$B_{2024}$ -- female spawning biomass in current year of model}\\
5ABC      & 26,500 & 26,500 & 33,200  & 23,500\\
3CD       & 11,200 & 10,200 & 15,700  & 13,500\\
5DE       & 12,000 & 12,100 & 13,400  & 16,100\\
Coastwide & 49,700 & 48,700 & 62,300  & 53,100\\
\multicolumn{5}{l}{$B_{2024}/B_0$ -- female spawning biomass depletion}\\
5ABC      & 0.474  & 0.485  & 0.501   & 0.568\\
3CD       & 0.597  & 0.563  & 0.692   & 1.010\\
5DE       & 0.635  & 0.662  & 0.626   & 1.220\\
Coastwide & 0.531  & 0.536  & 0.564   & 0.781\\
\hline  
\end{longtable}


\subsection{Prior distributions}

Descriptions of the prior distributions for the estimated parameters (without including recruitment deviations) are given in Table~\ref{tab:priors}.
A wide normal prior $\Norm$(10,10) was used for $\log R_0$; this often provides more stability in the model than using a uniform prior without affecting the estimation process.
Steepness was estimated using a beta distribution, with priors generated by \citet{Forrest-etal:2010}: $\beta$(0.67,0.17).
Catchability parameters $q_g$ were determined analytically by SS3 (using \code{float=1}).

Natural mortality priors, which were based loosely on MCMC medians from Table~1 of the 5ABC POP assessment in 2017 \citep{Haigh-etal:2018_pop5ABC}, used a normal prior of $\Norm$(0.06,0,018) for both sexes in the base run of the current stock assessment.
For two of the area-based models, priors on $M$ were tightened to achieve acceptable MCMC diagnostics (5ABC model used a 20\pc{} CV, 3CD model used a 10\pc{} CV).

Selectivity prior means were initially based on MCMC medians estimated from three previous POP stock assessments: Table~1 in \citet{Haigh-etal:2018_pop5ABC} for 5ABC, Table~G.2 in \citet{Edwards-etal:2014_pop3CD} for 3CD, and Table~G.2 in \citet{Edwards-etal:2014_pop5DE} for 5DE, and applying a 30\pc{} CV.
During the evolution of model runs, these normal priors were generalised and broadened to emulate the pseudo-uniform prior on $\log R_0$.
The priors used for $\mu_g$ were set to $\Norm$(10,10) for the fisheries and $\Norm$(12,12) for the surveys.
Similarly, the priors for $\log v_{\text{L}g}$ were set to $\Norm$(2,2) for the fisheries and $\Norm$(2.5,2.5) for the surveys.
These did not work well for three of the surveys due to noisy AF data, and so the priors for WCHG synoptic, GIG historical, and NMFS triennial were tightened to $\Norm$(12,3.6) for $\mu$ and $\Norm$(2.5,0.75) for $\log v_\text{L}$.

\subsection{MCMC properties}

The MCMC procedure used the `no U-turn sampling' (NUTS) algorithm \citep{Monnahan-Kristensen:2018, Monnahan-etal:2019} to produce \nSims{} iterations, parsing the workload into \nChains{} parallel chains (using the R~package \code{snowfall}, \citealt{R:2015_snowfall}).
For each chain, \cSims{} iterations were performed, discarding the first \cBurn{} samples as a `burn-in', leaving the final \cSamps{} samples for use in the MCMC analysis.
The parallel chains were then merged for a total of \Nmcmc{} samples to approximate the posterior distribution.
For the base and area runs, an excess of samples were thinned every \nThin{} samples; sensitivity runs were not thinned because sampling was not prolonged.
Code (bash and R) was supplied by Chris Grandin (DFO, pers. comm. 2023) to perform the MCMC simulations on a remote Linux server.

%%==========================================================
\section{REFERENCE POINTS, PROJECTIONS, AND ADVICE TO MANAGERS}

Advice to managers is given with respect to a suite of reference points.
The first set is based on MSY (maximum sustainable yield) and includes the provisional reference points of the DFO Precautionary Approach \citep{DFO-SAR:2006_pa}, namely 0.4$\Bmsy$ and 0.8$\Bmsy$ (and also provided are $\Bmsy$ and $\umsy$, which denote the estimated equilibrium spawning biomass and harvest rate at MSY, respectively). 
A second set of reference points, based on the current spawning biomass $B_{\currYear}$ and harvest rate $u_{\prevYear}$, is used to show the probability of the stock size increasing from the current female spawning biomass or decreasing from the current harvest rate.
A third set of reference points, based on $B_0$ (the estimated unfished equilibrium spawning biomass) is provided as an alternative to the $\Bmsy$ reference points.
See main text for further discussion.

The probability $\text{P}(B_{\finalYr} > 0.4\Bmsy)$ is calculated as the proportion of the \Nbase{} MCMC samples (after thinning) for which $B_{\finalYr} > 0.4\Bmsy$ (and similarly for the other biomass-based reference points).
For harvest rates, the probability $\text{P}(u_{\prevYear} < \umsy)$ is calculated so that both $B$- and $u$-based stock status indicators (and projections when $t=\Sexpr{currYear+1},...,\projYear$) state the probability of being in a `good' place.

Projections were made for \Sexpr{nprojYrs+1} years starting with the biomass for the start of \currYear.
All derived values in SS3 are for a start-of-year time period.
Therefore, if the end year in the data file is specified as \prevYear, derived quantities like spawning biomass $B_t$ are estimated to start of year \prevYear.
By default, SS3 will project forward at least one year so that catch in \prevYear{} can be applied and derived quantities will be generated for \currYear{} (one-year forecast).
Therefore, in the file \code{forecast.ss}, a user needs to specify the current year plus any additional forecast years (e.g., a 10-yr forecast would need 11 specified catches from \currYear{} to \Sexpr{projYear}).
Additionally, if a user needs generational forecasts (e.g, three POP generations = 75 years), then 76 forecast years need to be specified before any MCMC runs are attempted.

%In this stock assessment, the default catch for projections was the average catch from \Sexpr{paste0(currYear-1-c(5,1),collapse=" to ")}, which equalled \Sexpr{texThatVec(paste0(avgCat,"\\\\,t"),simplify=FALSE)} for \Sexpr{texThatVec(stock.subs,simplify=FALSE)}, respectively.
For decision tables, a range of constant catch strategies were used, from 0 to \policyMax{} at \policyInc{} increments.
%For each strategy, projections were performed for each of the \Nbase{} MCMC samples after thinning (resulting in posterior distributions of future spawning biomass).
Recruitments were randomly calculated using \eref{Rt} (i.e.~based on lognormal recruitment deviations from the estimated stock-recruitment curve), using randomly generated values of $\epsilon_t \sim \mbox{Normal}(0, \sigma_R^2)$. 
Unfortunately, SS3 calculates projected recruitment deviations at the time of the MCMC runs and so the user should be aware that changing the catch policy after the MCMCs had been performed is not possible.
In Awatea, the \code{-mceval} switch can generate a user-specified time series of $\left\{ \epsilon_t \right\}$ for each of the MCMC samples, which means that different catch policies can be generated after the MCMC analysis.

%\clearpage
\section{SS3 INPUTS} \label{s:inputs}

Input files for each model run are hosted on Github in the code repository \href{https://github.com/pbs-software/pbs-synth}{PBSsynth}.
The file names comprise \code{`starter.ss'}, \code{`forecast.ss'}, \code{`data.xx.yy.ss'}, and \code{`control.xx.yy.ss'}, where xx~=\,run number and yy~=\,reweight number. 
%See the \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/00ReadMe.txt}{synopsis} of runs used in the 2023 POP assessment for more detail.

Synopsis of runs:\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/00ReadMe.txt}{00ReadMe.txt} -- Information on the runs used in 2023 POP

Base run:\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Base/R21v3/21.01}{Run21v3} -- BC coastwide multi-area model

Area runs:\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/5ABC/R24v1/24.01}{Run24v1} -- 5ABC single-area model\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/3CD/R25v1/25.01}{Run25v1} -- 3CD single-area model\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/5DE/R26v1/26.01}{Run26v1} -- 5DE single-area model

Sensitivity runs (MCMC):\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S01.R17v18/17.00}{S01.R17v18} -- use Dirichlet-multinomial parameterisation\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S02.R27v1/27.01}{S02.R27v1} -- fix parameter Rdist for 5ABC to 0\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S03.R28v1/28.01}{S03.R28v1} -- fix parameter Rdist for 3CD to 0\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S04.R29v1/29.01}{S04.R29v1} -- apply no ageing error\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S05.R30v1/30.01}{S05.R30v1} -- use smoothed ageing error from age-reader CVs\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S06.R31v1/31.01}{S06.R31v1} -- use constant-CV ageing error\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S07.R32v1/32.01}{S07.R32v1} -- reduce commercial catch (1965-95) by 30\pc{}\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S08.R33v1/33.01}{S08.R33v1} -- increase commercial catch (1965-95) by 50\pc{}\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S09.R34v1/34.01}{S09.R34v1} -- reduce sigmaR to 0.6 (from 0.9)\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S10.R35v1/35.01}{S10.R35v1} -- increase sigmaR to 1.2 (from 0.9)\\

Sensitivity runs (MPD):\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S11.R22v2/22.01}{S11.R22v2} -- use separate midwater and bottom trawl fleets for 3CD and 5ABC\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S12.R36v2/36.01}{S12.R36v2} -- add HS synoptic survey to 5DE\\
\tab \href{https://github.com/pbs-software/pbs-synth/tree/master/PBSsynth/inst/input/2023/POP/CST/Sens/S13.R37v1/37.01}{S13.R37v1} -- use empirical proportions mature instead of MLE fit\\

%\subsection{starter.ss}
%%%\usefont{enc}{family}{series}{shape}
%\usefont{T1}{zi4}{m}{n}%\footnotesize  *****cannot find inconsolata
%%{\scriptsize
%%\begin{lstlisting} %% need to put this in each of the four SS3 input files
%\input{starter.ss}
%\subsection{data.ss}
%\input{data.17.00.ss}
%\subsection{control.ss}
%\input{control.17.00.ss}
%\subsection{forecast.ss}
%\input{forecast.ss}
%
%%\end{lstlisting}
%%}
%\usefont{\encodingdefault}{\familydefault}{\seriesdefault}{\shapedefault}%\normal

\bigskip
\bibliographystyle{resDoc}
%% Use for appendix bibliographies only: (http://www.latex-community.org/forum/viewtopic.php?f=5&t=4089)
\renewcommand\bibsection{\section{REFERENCES -- MODEL EQUATIONS}}
\bibliography{C:/Users/haighr/Files/GFish/CSAP/Refs/CSAPrefs}

\end{document}
